# Generated by Django 5.1.7 on 2025-04-07 04:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('identificacion', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identificación (NIT/Cédula)')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='inventario.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='IngresoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora Ingreso')),
                ('proveedor_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Información Proveedor/Origen')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia (Factura Compra, Remisión, etc.)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Ingreso a Bodega',
                'verbose_name_plural': 'Ingresos a Bodega',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Pedido')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado del Pedido')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento Aplicado (%)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='inventario.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Devolución')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo General')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventario.cliente', verbose_name='Cliente que Devuelve')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Procesa')),
                ('pedido_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_asociadas', to='inventario.pedido', verbose_name='Pedido Original (Opcional)')),
            ],
            options={
                'verbose_name': 'Devolución de Cliente',
                'verbose_name_plural': 'Devoluciones de Clientes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=50, verbose_name='Referencia Base')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('talla', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Color')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('unidad_medida', models.CharField(default='UND', max_length=20, verbose_name='Unidad de Medida')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en Bodega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='¿Está Activo?')),
            ],
            options={
                'verbose_name': 'Producto (Variante)',
                'verbose_name_plural': 'Productos (Variantes)',
                'ordering': ['referencia', 'nombre', 'color', 'talla'],
                'constraints': [models.UniqueConstraint(fields=('referencia', 'talla', 'color'), name='variante_unica')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Movida')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_DEVOLUCION', 'Entrada por Devolución'), ('SALIDA_VENTA', 'Salida por Venta'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_DEVOLUCION', 'Salida por Devolución'), ('SALIDA_OTRO', 'Salida por Otro Motivo'), ('ENTRADA_OTRO', 'Entrada por Otro Motivo')], max_length=25, verbose_name='Tipo de Movimiento')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia (ID Pedido, Factura, etc.)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_hora', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de Contacto (Opcional)')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Interno (Opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['user__username'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='inventario.vendedor', verbose_name='Vendedor'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('verificado_bodega', models.BooleanField(default=False, verbose_name='Verificado Bodega')),
                ('cantidad_verificada', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Verificada')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.pedido', verbose_name='Pedido Asociado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='DetalleIngresoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario Ingreso (Opcional)')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ingresobodega', verbose_name='Ingreso Asociado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ingreso', to='inventario.producto', verbose_name='Producto Ingresado')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso a Bodega',
                'verbose_name_plural': 'Detalles de Ingreso a Bodega',
                'unique_together': {('ingreso', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Devuelta')),
                ('estado_producto', models.CharField(choices=[('BUENO', 'Buen estado (Reingresa a stock)'), ('DEFECTUOSO', 'Defectuoso (Revisión/Reparación)'), ('DESECHAR', 'Para Desechar')], default='BUENO', max_length=15, verbose_name='Estado del Producto Devuelto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.devolucioncliente', verbose_name='Devolución Asociada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_devueltos', to='inventario.producto', verbose_name='Producto Devuelto')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
                'unique_together': {('devolucion', 'producto')},
            },
        ),
    ]
