# Generated by Django 5.1.7 on 2025-05-02 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_pedido_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(blank=True, help_text='ID interno o código del empleado de bodega', max_length=50, null=True, unique=True)),
                ('area_asignada', models.CharField(blank=True, help_text='Área específica de la bodega asignada', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el perfil de bodega está activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_bodega', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal de Bodega',
                'verbose_name_plural': 'Personal de Bodega',
                'ordering': ['user__username'],
            },
        ),
    ]
