# Generated by Django 5.1.7 on 2025-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_personalbodega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalbodega',
            options={},
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('DAMA', 'Dama'), ('CABALLERO', 'Caballero'), ('UNISEX', 'Unisex')], db_index=True, default='UNISEX', help_text='Género OBLIGATORIO al que pertenece la referencia', max_length=10),
        ),
    ]
