# Generated by Django 5.1.7 on 2025-05-07 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_personalbodega_options_producto_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Conteo')),
                ('cantidad_sistema_antes', models.IntegerField(verbose_name='Cantidad en Sistema (Antes del Conteo)')),
                ('cantidad_fisica_contada', models.IntegerField(verbose_name='Cantidad Física Contada')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_inventario', to='inventario.producto', verbose_name='Producto Contado')),
                ('usuario_conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Contó')),
            ],
            options={
                'verbose_name': 'Registro de Conteo de Inventario',
                'verbose_name_plural': 'Registros de Conteos de Inventario',
                'ordering': ['-fecha_conteo', 'producto'],
            },
        ),
    ]
