# Generated by Django 5.1.7 on 2025-05-07 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_conteoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteoinventario',
            name='fecha_actualizacion_stock',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Efectiva del Ajuste'),
        ),
        migrations.AddField(
            model_name='conteoinventario',
            name='motivo_conteo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo del Conteo/Ajuste'),
        ),
        migrations.AddField(
            model_name='conteoinventario',
            name='notas_generales',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Generales del Conteo'),
        ),
        migrations.AddField(
            model_name='conteoinventario',
            name='revisado_con',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Revisado/Contado Con'),
        ),
    ]
