# Generated by Django 5.1.7 on 2025-05-07 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_conteoinventario_fecha_actualizacion_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteoinventario',
            options={'ordering': ['cabecera_conteo', 'producto'], 'verbose_name': 'Detalle de Conteo de Inventario', 'verbose_name_plural': 'Detalles de Conteos de Inventario'},
        ),
        migrations.CreateModel(
            name='CabeceraConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Efectiva del Conteo')),
                ('motivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo del Conteo')),
                ('revisado_con', models.CharField(blank=True, max_length=150, null=True, verbose_name='Revisado Con')),
                ('notas_generales', models.TextField(blank=True, null=True, verbose_name='Notas Generales')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Cabecera de Conteo de Inventario',
                'verbose_name_plural': 'Cabeceras de Conteos de Inventario',
                'ordering': ['-fecha_hora_registro'],
            },
        ),
        migrations.AddField(
            model_name='conteoinventario',
            name='cabecera_conteo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_conteo', to='inventario.cabeceraconteo', verbose_name='Cabecera del Conteo'),
        ),
    ]
