# Generated by Django 5.1.7 on 2025-05-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_conteoinventario_motivo_conteo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteoinventario',
            name='motivo_conteo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo del Conteo/Ajuste'),
        ),
        migrations.AlterField(
            model_name='conteoinventario',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Adicionales'),
        ),
        migrations.AlterField(
            model_name='conteoinventario',
            name='notas_generales',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Generales del Conteo'),
        ),
    ]
