# Generated by Django 5.1.7 on 2025-05-08 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_conteoinventario_motivo_conteo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteoinventario',
            name='cabecera_conteo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_conteo', to='inventario.cabeceraconteo', verbose_name='Cabecera del Conteo'),
        ),
    ]
