# Generated by Django 5.1.7 on 2025-05-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_conteoinventario_cabecera_conteo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoCartera',
        ),
    ]
