# Generated by Django 5.1.7 on 2025-05-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_documentocartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocartera',
            name='codigo_vendedor_cartera',
            field=models.CharField(blank=True, db_index=True, help_text='Código del vendedor según el archivo de cartera (VENDEDOR)', max_length=20, null=True),
        ),
    ]
