# Generated by Django 5.1.7 on 2025-05-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_documentocartera_codigo_vendedor_cartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras único para esta variante de producto (Ref+Talla+Color).', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False)), fields=('codigo_barras',), name='codigo_barras_unico_no_nulo'),
        ),
    ]
