# Generated by Django 5.2.1 on 2025-10-19 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_empresa_tallas_dama_display_and_more'),
        ('notificaciones', '0003_populate_notificacion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_empresa', to='clientes.empresa'),
        ),
    ]
