# Generated by Django 5.2.1 on 2025-05-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('LF', 'Factura Oficial'), ('FYN', 'Remisión')], db_index=True, max_length=3)),
                ('numero_documento', models.CharField(db_index=True, max_length=50)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nombre_vendedor_cartera', models.CharField(blank=True, help_text='Nombre del vendedor según el archivo de cartera (columna NOMVENDEDOR)', max_length=150, null=True)),
                ('codigo_vendedor_cartera', models.CharField(blank=True, db_index=True, help_text='Código del vendedor según el archivo de cartera (VENDEDOR)', max_length=20, null=True)),
                ('ultima_actualizacion_carga', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cartera', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento de Cartera',
                'verbose_name_plural': 'Documentos de Cartera',
                'ordering': ['cliente', 'fecha_vencimiento'],
                'unique_together': {('cliente', 'tipo_documento', 'numero_documento')},
            },
        ),
    ]
