# Generated by Django 5.2.1 on 2025-10-05 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('LF', 'Factura Oficial'), ('FYN', 'Remisión')], db_index=True, max_length=3)),
                ('numero_documento', models.CharField(db_index=True, max_length=50)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nombre_vendedor_cartera', models.CharField(blank=True, help_text='Nombre del vendedor según el archivo de cartera (columna NOMVENDEDOR)', max_length=150, null=True)),
                ('codigo_vendedor_cartera', models.CharField(blank=True, db_index=True, help_text='Código del vendedor según el archivo de cartera (VENDEDOR)', max_length=20, null=True)),
                ('ultima_actualizacion_carga', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cartera_cliente', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cartera', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Documento de Cartera',
                'verbose_name_plural': 'Documentos de Cartera',
                'ordering': ['empresa', 'cliente', 'fecha_vencimiento'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cliente', 'numero_documento', 'tipo_documento'), name='restriccion_factura_unica_por_cliente')],
            },
        ),
        migrations.CreateModel(
            name='PerfilImportacionCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(help_text="Nombre único para identificar este perfil (ej: 'Formato Contable S.A.S.')", max_length=100, unique=True)),
                ('fila_inicio_header', models.PositiveIntegerField(default=3, help_text='Número de la fila en Excel donde comienzan los datos (ej: si los datos empiezan en la fila 4, poner 3).')),
                ('columna_id_cliente', models.CharField(default='CODIGO', max_length=50)),
                ('columna_numero_documento', models.CharField(default='DOCUMENTO', max_length=50)),
                ('columna_fecha_documento', models.CharField(default='FECHADOC', max_length=50)),
                ('columna_fecha_vencimiento', models.CharField(default='FECHAVEN', max_length=50)),
                ('columna_saldo', models.CharField(default='SALDOACT', max_length=50)),
                ('columna_nombre_vendedor', models.CharField(default='NOMVENDEDOR', max_length=50)),
                ('columna_codigo_vendedor', models.CharField(default='VENDEDOR', max_length=50)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece este formato de archivo.', on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_importacion', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Importación de Cartera',
                'verbose_name_plural': 'Perfiles de Importación de Cartera',
                'unique_together': {('empresa', 'nombre_perfil')},
            },
        ),
    ]
