# Generated by Django 5.2.1 on 2025-10-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilimportacioncartera',
            name='columna_codigo_vendedor',
            field=models.CharField(blank=True, default='VENDEDOR', help_text='(Opcional) Déjalo en blanco si el archivo no tiene esta columna.', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilimportacioncartera',
            name='columna_fecha_documento',
            field=models.CharField(blank=True, default='FECHADOC', help_text='(Opcional) Déjalo en blanco si el archivo no tiene esta columna.', max_length=50),
        ),
    ]
