# Generated by Django 5.2.1 on 2025-10-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_alter_perfilimportacioncartera_columna_codigo_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilimportacioncartera',
            name='columna_codigo_vendedor',
            field=models.CharField(default='VENDEDOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilimportacioncartera',
            name='columna_fecha_documento',
            field=models.CharField(default='FECHADOC', max_length=50),
        ),
    ]
