# Generated by Django 5.2.1 on 2025-10-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_alter_perfilimportacioncartera_columna_codigo_vendedor_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentocartera',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente', 'numero_documento', 'tipo_documento'), name='restriccion_factura_unica_por_cliente'),
        ),
    ]
