# Generated by Django 5.2.1 on 2025-05-25 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceCatalogoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional para identificar el enlace.', max_length=255)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('expira_el', models.DateTimeField()),
                ('activo', models.BooleanField(default=True, help_text='Permite desactivar el enlace manualmente antes de que expire.')),
                ('veces_usado', models.PositiveIntegerField(default=0, help_text='Contador de cuántas veces se ha accedido al enlace (opcional).')),
            ],
            options={
                'verbose_name': 'Enlace Temporal de Catálogo',
                'verbose_name_plural': 'Enlaces Temporales de Catálogo',
                'ordering': ['-creado_el'],
            },
        ),
    ]
