# Generated by Django 5.2.1 on 2026-07-16 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_usa_shopify'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text="Debe coincidir exactamente con el valor 'categoria' usado en core/panel_config.py", max_length=100, verbose_name='Módulo (categoría del panel)')),
                ('activo', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Módulo Contratado por Empresa',
                'verbose_name_plural': 'Módulos Contratados por Empresa',
                'constraints': [models.UniqueConstraint(fields=('empresa', 'categoria'), name='un_modulo_por_empresa_y_categoria')],
            },
        ),
    ]
