# Generated by Django 5.2.1 on 2026-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_usa_shopify'),
        ('core', '0002_moduloempresa'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moduloempresa',
            name='un_modulo_por_empresa_y_categoria',
        ),
        migrations.AddField(
            model_name='moduloempresa',
            name='url_nombre',
            field=models.CharField(blank=True, default='', help_text="Vacío = aplica a toda la categoría. Con valor (ej. 'bodega:lista_bodegas') = solo esa opción puntual.", max_length=150, verbose_name='Opción Específica (opcional)'),
        ),
        migrations.AddConstraint(
            model_name='moduloempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'categoria', 'url_nombre'), name='un_modulo_por_empresa_categoria_item'),
        ),
    ]
