# Generated by Django 5.2.1 on 2025-07-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_empresa_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('m', 'Metros'), ('un', 'Unidades'), ('kg', 'Kilogramos')], max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_insumos', to='costeo_jeans.costeo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_jeans.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_costo', models.CharField(choices=[('unidad', 'Por unidad'), ('hora', 'Por hora'), ('lote', 'Por lote')], max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_procesos', to='costeo_jeans.costeo')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_jeans.proceso')),
            ],
        ),
    ]
