# Generated by Django 5.2.1 on 2025-09-24 06:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confeccionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento_identidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('aplica_iva', models.BooleanField(default=False, help_text='Marcar si este confeccionista factura con IVA')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Costeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de venta final de cada unidad.', max_digits=12)),
                ('porcentaje_descuento_cliente', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento para el cliente (ej: 10 para 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('porcentaje_comision_vendedor', models.DecimalField(decimal_places=2, default=6.0, help_text='Porcentaje de comisión para el vendedor (ej: 6 para 6%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Gastos Administrativos, Ganancia, Transporte', max_length=100)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', '% del Subtotal (Insumos + Procesos)'), ('FIJO_UNIDAD', '$ Valor Fijo por Unidad')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='El valor numérico. Si es porcentaje, escribir 10 para 10%.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('incluir_por_defecto', models.BooleanField(default=True, help_text='Marcar si este costo debe añadirse automáticamente a cada nuevo costeo.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_costos_fijos', to='costeo_jeans.costeo')),
                ('costo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_jeans.costofijo')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('TELA', 'Tela'), ('AVIO', 'Avío / Otros')], default='AVIO', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('m', 'Metros'), ('un', 'Unidades'), ('kg', 'Kilogramos')], max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_unitario', models.DecimalField(decimal_places=4, default=0, help_text='Cantidad o metros necesarios para UNA SOLA UNIDAD del producto.', max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, editable=False, help_text='Cantidad total calculada para toda la producción.', max_digits=10)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_insumos', to='costeo_jeans.costeo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_jeans.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Ingreso)'), ('SALIDA', 'Salida (Uso en Producción)'), ('AJUSTE', 'Ajuste Manual')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('costeo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costeo_jeans.costeo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='costeo_jeans.insumo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PROCESO', 'Proceso Industrial'), ('CONFECCION', 'Confección por Prenda')], default='PROCESO', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TarifaConfeccionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo del servicio SIN IVA.', max_digits=10)),
                ('confeccionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='costeo_jeans.confeccionista')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='costeo_jeans.proceso')),
            ],
            options={
                'unique_together': {('confeccionista', 'proceso')},
            },
        ),
        migrations.CreateModel(
            name='DetalleProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario_registrado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('aplica_iva_registrado', models.BooleanField(default=False, editable=False)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_procesos', to='costeo_jeans.costeo')),
                ('tarifa', models.ForeignKey(blank=True, help_text='Selecciona el proceso y quién lo realiza', null=True, on_delete=django.db.models.deletion.PROTECT, to='costeo_jeans.tarifaconfeccionista')),
            ],
        ),
    ]
