# Generated by Django 5.2.1 on 2026-07-17 21:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0001_initial'),
        ('productos', '0016_referenciacolor_shopify_borrador_por_agotado'),
    ]

    operations = [
        # RenameField (no RemoveField+AddField) para PRESERVAR el precio de
        # venta que ya tenían los costeos existentes -- pasa a ser su
        # "precio manual" (sigue teniendo prioridad sobre el sugerido, así
        # que el histórico no cambia de valor).
        migrations.RenameField(
            model_name='costeo',
            old_name='precio_venta_unitario',
            new_name='precio_venta_manual',
        ),
        migrations.AlterField(
            model_name='costeo',
            name='precio_venta_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Solo diligéncialo si necesitas FORZAR un precio distinto al sugerido (ej. para igualar un precio de mercado). Si lo dejas vacío, se usa el precio sugerido calculado a partir del costo y el margen deseado.', max_digits=12, null=True, verbose_name='Precio de venta (manual)'),
        ),
        migrations.AddField(
            model_name='costeo',
            name='margen_deseado',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='% de utilidad deseado SOBRE EL PRECIO DE VENTA final (no sobre el costo). El precio de venta se calcula solo: Precio = Costo ÷ (1 − margen/100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('99.99'))]),
        ),
        migrations.AddField(
            model_name='costeo',
            name='referencia_color',
            field=models.ForeignKey(blank=True, help_text='Referencia+color real del catálogo (opcional -- déjalo vacío si aún no existe como producto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costeos', to='productos.referenciacolor'),
        ),
        migrations.AddField(
            model_name='detalleinsumo',
            name='porcentaje_desperdicio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de merma/desperdicio sobre el consumo neto (ej. 10 para 10%). Estándar en tela por ancho de rollo/trazo de corte; en avíos normalmente 0.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='costofijo',
            name='nombre',
            field=models.CharField(help_text="Ej: Gastos Administrativos, Transporte, Empaque. La ganancia/margen ya NO va aquí -- se define en 'Margen Deseado' al crear cada costeo.", max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleinsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Cantidad total calculada para toda la producción (incluye el % de desperdicio).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleinsumo',
            name='consumo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cantidad o metros necesarios para UNA SOLA UNIDAD del producto (consumo neto, sin desperdicio).', max_digits=10),
        ),
    ]
