# Generated by Django 5.2.1 on 2025-07-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
