# Generated by Django 5.2.1 on 2026-07-17 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_costo_unitario_registrado(apps, schema_editor):
    """
    Los DetalleInsumo que ya existían nunca tuvieron un costo congelado --
    sin este backfill, quedarían con costo_unitario_registrado=0 (el default
    del campo nuevo) y todos los costeos históricos caerían a costo $0. Se
    usa el costo ACTUAL del insumo como el mejor dato disponible (es lo
    mismo que mostraban antes de este cambio, ya que antes se leía en vivo).
    """
    DetalleInsumo = apps.get_model('costeo_jeans', 'DetalleInsumo')
    for detalle in DetalleInsumo.objects.select_related('insumo').all():
        detalle.costo_unitario_registrado = detalle.insumo.costo_unitario
        detalle.save(update_fields=['costo_unitario_registrado'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0002_remove_costeo_precio_venta_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='stock_descontado',
            field=models.BooleanField(default=False, editable=False, help_text='Indica si ya se descontaron los insumos del inventario para este costeo (se activa al Finalizar, se revierte al Reabrir).'),
        ),
        migrations.AddField(
            model_name='detalleinsumo',
            name='costo_unitario_registrado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='costeo',
            name='cantidad_producida',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Se calcula solo, sumando el desglose de producción por talla.'),
        ),
        migrations.CreateModel(
            name='DetalleCantidadTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(help_text='Ej: 28, 30, S, M...', max_length=20)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_tallas', to='costeo_jeans.costeo')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('costeo', 'talla')},
            },
        ),
        migrations.RunPython(backfill_costo_unitario_registrado, noop),
    ]
