# Generated by Django 5.2.1 on 2025-07-05 23:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_empresa_telefono'),
        ('costeo_jeans', '0003_remove_proceso_tipo_costo_proceso_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Gastos Administrativos, Ganancia, Transporte', max_length=100)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', '% del Subtotal (Insumos + Procesos)'), ('FIJO_UNIDAD', '$ Valor Fijo por Unidad')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='El valor numérico. Si es porcentaje, escribir 10 para 10%.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('incluir_por_defecto', models.BooleanField(default=True, help_text='Marcar si este costo debe añadirse automáticamente a cada nuevo costeo.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_costos_fijos', to='costeo_jeans.costeo')),
                ('costo_fijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_jeans.costofijo')),
            ],
        ),
    ]
