# Generated by Django 5.2.1 on 2025-07-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0004_costofijo_detallecostofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado')], default='BORRADOR', max_length=20),
        ),
    ]
