# Generated by Django 5.2.1 on 2025-07-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0005_costeo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('TELA', 'Tela'), ('AVIO', 'Avío / Otros')], default='AVIO', max_length=20),
        ),
    ]
