# Generated by Django 5.2.1 on 2025-07-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_empresa_telefono'),
        ('costeo_jeans', '0006_insumo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproceso',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='costo',
        ),
        migrations.AddField(
            model_name='detalleproceso',
            name='aplica_iva_registrado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='detalleproceso',
            name='costo_unitario_registrado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleproceso',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TarifaConfeccionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo del servicio SIN IVA.', max_digits=10)),
                ('confeccionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='costeo_jeans.confeccionista')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='costeo_jeans.proceso')),
            ],
            options={
                'unique_together': {('confeccionista', 'proceso')},
            },
        ),
        migrations.AddField(
            model_name='detalleproceso',
            name='tarifa',
            field=models.ForeignKey(blank=True, help_text='Selecciona el proceso y quién lo realiza', null=True, on_delete=django.db.models.deletion.PROTECT, to='costeo_jeans.tarifaconfeccionista'),
        ),
    ]
