# Generated by Django 5.2.1 on 2025-07-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0007_remove_detalleproceso_proceso_remove_proceso_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproceso',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
