# Generated by Django 5.2.1 on 2025-07-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0009_detalleinsumo_consumo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='precio_venta_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de venta final de cada unidad.', max_digits=12),
        ),
    ]
