# Generated by Django 5.2.1 on 2025-07-11 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0010_costeo_precio_venta_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeo',
            name='porcentaje_comision_vendedor',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Porcentaje de comisión para el vendedor (ej: 6 para 6%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='costeo',
            name='porcentaje_descuento_cliente',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento para el cliente (ej: 10 para 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
