# Generated by Django 5.2.1 on 2025-07-11 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_jeans', '0011_costeo_porcentaje_comision_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Ingreso)'), ('SALIDA', 'Salida (Uso en Producción)'), ('AJUSTE', 'Ajuste Manual')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('costeo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costeo_jeans.costeo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='costeo_jeans.insumo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
