# Generated by Django 5.2.1 on 2026-07-16 03:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0010_bodega_disponible_venta_puntoventa_and_more'),
        ('clientes', '0005_empresa_usa_shopify'),
        ('productos', '0008_alter_producto_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Apertura')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Inicial Declarado')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Cierre')),
                ('saldo_final_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Efectivo Contado al Cierre')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia (Contado - Esperado)')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10, verbose_name='Estado del Turno')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_caja', to='bodega.bodega', verbose_name='Bodega / Caja de Punto de Venta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_caja', to='clientes.empresa', verbose_name='Empresa')),
                ('usuario_cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_caja_abiertos', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='VentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('consecutivo', models.PositiveIntegerField(verbose_name='Número de Recibo')),
                ('total_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de la Venta')),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='COMPLETADA', max_length=12, verbose_name='Estado')),
                ('cliente', models.ForeignKey(blank=True, help_text='Vacío = Cliente Mostrador (venta genérica sin cliente registrado).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos', to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pos', to='clientes.empresa', verbose_name='Empresa')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='puntoventa.turnocaja', verbose_name='Turno de Caja')),
            ],
            options={
                'verbose_name': 'Venta de Punto de Venta',
                'verbose_name_plural': 'Ventas de Punto de Venta',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PagoVentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, verbose_name='Método de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='puntoventa.ventapos', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta POS',
                'verbose_name_plural': 'Pagos de Venta POS',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('precio_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si el cajero ajustó el precio de esta línea, el valor final queda aquí.', max_digits=12, null=True, verbose_name='Precio Ajustado Manualmente')),
                ('motivo_override', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo del Ajuste de Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_pos_detalle', to='productos.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='puntoventa.ventapos', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta POS',
                'verbose_name_plural': 'Detalles de Venta POS',
            },
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('bodega',), name='un_turno_abierto_por_bodega'),
        ),
        migrations.AddConstraint(
            model_name='ventapos',
            constraint=models.UniqueConstraint(fields=('empresa', 'consecutivo'), name='consecutivo_unico_por_empresa_pos'),
        ),
    ]
