# Generated by Django 5.2.1 on 2026-07-16 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_bodega_disponible_venta_puntoventa_and_more'),
        ('clientes', '0005_empresa_usa_shopify'),
        ('productos', '0008_alter_producto_ubicacion'),
        ('puntoventa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventapos',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo aplica a pagos en efectivo: cuánto entregó físicamente el cliente.', max_digits=12, null=True, verbose_name='Monto Recibido en Efectivo'),
        ),
        migrations.CreateModel(
            name='PrecioEspecialPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_especial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Especial (Saldo)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales_pos', to='bodega.bodega', verbose_name='Bodega de Punto de Venta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales_pos', to='clientes.empresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales_pos', to='productos.producto', verbose_name='Producto')),
                ('usuario_actualizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Precio Especial de Punto de Venta',
                'verbose_name_plural': 'Precios Especiales de Punto de Venta',
                'constraints': [models.UniqueConstraint(fields=('bodega', 'producto'), name='un_precio_especial_por_producto_y_bodega')],
            },
        ),
    ]
