# Generated by Django 5.2.1 on 2026-07-16 04:48

import puntoventa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntoventa', '0002_pagoventapos_monto_recibido_precioespecialpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventapos',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, null=True, upload_to=puntoventa.models.ruta_comprobante_transferencia, verbose_name='Foto del Comprobante de Transferencia'),
        ),
    ]
