# Generated by Django 5.2.1 on 2026-07-16 05:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_usa_shopify'),
        ('productos', '0008_alter_producto_ubicacion'),
        ('puntoventa', '0003_pagoventapos_comprobante_transferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapos',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas / Observaciones'),
        ),
        migrations.CreateModel(
            name='DevolucionCambioPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('DEVOLUCION', 'Devolución (Reembolso)'), ('CAMBIO', 'Cambio de Producto')], max_length=12, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('total_valor_devuelto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de lo Devuelto')),
                ('total_valor_entregado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de lo Entregado (Cambio)')),
                ('monto_reembolsado_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Reembolsado en Efectivo')),
                ('metodo_pago_adicional', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, null=True, verbose_name='Método de Pago de la Diferencia (si el cliente debe más)')),
                ('monto_cobrado_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cobrado Adicional')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_pos', to='clientes.empresa', verbose_name='Empresa')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_cambios', to='puntoventa.turnocaja', verbose_name='Turno que Procesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('venta_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_cambios', to='puntoventa.ventapos', verbose_name='Venta POS Original')),
            ],
            options={
                'verbose_name': 'Devolución/Cambio de Punto de Venta',
                'verbose_name_plural': 'Devoluciones/Cambios de Punto de Venta',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaCambioPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Entregada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_cambio_pos', to='productos.producto', verbose_name='Producto Entregado')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_entregados', to='puntoventa.devolucioncambiopos', verbose_name='Devolución/Cambio')),
            ],
            options={
                'verbose_name': 'Detalle de Producto Entregado en Cambio',
                'verbose_name_plural': 'Detalles de Productos Entregados en Cambio',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Devuelta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario (de la venta original)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('detalle_venta_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_detalle', to='puntoventa.detalleventapos', verbose_name='Línea de la Venta Original')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_devueltos', to='puntoventa.devolucioncambiopos', verbose_name='Devolución/Cambio')),
            ],
            options={
                'verbose_name': 'Detalle de Producto Devuelto',
                'verbose_name_plural': 'Detalles de Productos Devueltos',
            },
        ),
    ]
