# Generated by Django 5.2.1 on 2025-05-17 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de Contacto (Opcional)')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Interno (Opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['user__username'],
            },
        ),
    ]
