# Generated by Django 5.2.1 on 2025-07-01 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de Contacto (Opcional)')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Interno (Opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='clientes.empresa', verbose_name='Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['empresa', 'user__first_name', 'user__last_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo_interno__isnull', False)), fields=('empresa', 'codigo_interno'), name='unique_codigo_vendedor_por_empresa'), models.UniqueConstraint(fields=('empresa', 'user'), name='unique_usuario_vendedor_por_empresa')],
            },
        ),
    ]
