# Generated by Django 5.2.1 on 2025-09-24 06:37

import django.db.models.deletion
import prospectos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificación (NIT/Cédula)')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_ESTUDIO', 'En Estudio de Crédito'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('notas_evaluacion', models.TextField(blank=True, null=True, verbose_name='Notas de Evaluación de Cartera')),
                ('documento_rechazo', models.FileField(blank=True, null=True, upload_to=prospectos.models.ruta_guardado_documento_rechazo, verbose_name='Documento de Rechazo (Opcional)')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.ciudad', verbose_name='Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectos', to='clientes.empresa', verbose_name='Empresa')),
                ('vendedor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'permissions': [('aprobar_prospecto_cartera', 'Puede aprobar solicitudes de prospectos (Cartera)'), ('rechazar_prospecto_cartera', 'Puede rechazar solicitudes de prospectos (Cartera)')],
                'unique_together': {('empresa', 'identificacion')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RUT', 'RUT'), ('CAMARA_COMERCIO', 'Cámara de Comercio'), ('REFERENCIAS', 'Referencias'), ('PAGARE', 'Pagaré Firmado'), ('TRATAMIENTO_DATOS', 'Autorización Tratamiento de Datos'), ('CEDULA', 'Cédula de Ciudadanía'), ('OTRO', 'Otro Documento')], max_length=30, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='documentos_prospectos/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='prospectos.prospecto', verbose_name='Prospecto Asociado')),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
            },
        ),
    ]
