# Generated by Django 5.2.1 on 2025-10-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='notas_vendedor',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Vendedor'),
        ),
    ]
