# Generated by Django 5.2.1 on 2025-09-24 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos_online', '0001_initial'),
        ('productos', '0001_initial'),
        ('prospectos', '0001_initial'),
        ('vendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido_empresa', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Número de Pedido por Empresa')),
                ('tipo_pedido', models.CharField(choices=[('ESTANDAR', 'Estándar'), ('ONLINE', 'Online')], default='ESTANDAR', max_length=10, verbose_name='Tipo de Pedido')),
                ('forma_pago', models.CharField(choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado'), ('ADDI', 'Addi'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('OTRO_ONLINE', 'Otro Pago Online')], default='CREDITO', max_length=20, verbose_name='Forma de Pago')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_pago/', verbose_name='Comprobante de Pago')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Pedido')),
                ('estado', models.CharField(choices=[('PENDIENTE_CLIENTE', 'Pendiente por Aprobación de Cliente'), ('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION_CARTERA', 'Pendiente Aprobación Cartera'), ('RECHAZADO_CARTERA', 'Rechazado por Cartera'), ('PENDIENTE_APROBACION_ADMIN', 'Pendiente Aprobación Administración'), ('RECHAZADO_ADMIN', 'Rechazado por Administración'), ('APROBADO_ADMIN', 'Aprobado por Administración (Listo Bodega)'), ('PROCESANDO', 'Procesando en Bodega'), ('COMPLETADO', 'Completado en Bodega'), ('ENVIADO_INCOMPLETO', 'Enviado Incompleto'), ('LISTO_BODEGA_DIRECTO', 'Listo para Bodega (Directo)'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('CAMBIO_REGISTRADO', 'Cambio de Producto Registrado')], default='BORRADOR', max_length=35, verbose_name='Estado del Pedido')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Observaciones del Vendedor')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento Aplicado (%)')),
                ('token_descarga_fotos', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('motivo_cartera', models.TextField(blank=True, null=True, verbose_name='Motivo/Notas Cartera')),
                ('fecha_decision_cartera', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión Cartera')),
                ('motivo_admin', models.TextField(blank=True, null=True, verbose_name='Motivo/Notas Administración')),
                ('fecha_decision_admin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión Administración')),
                ('mostrar_precios_pdf', models.BooleanField(default=True, verbose_name='Mostrar Precios en PDF')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_estandar', to='clientes.cliente', verbose_name='Cliente')),
                ('cliente_online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_online_rel', to='pedidos_online.clienteonline', verbose_name='Cliente Online')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.empresa', verbose_name='Empresa')),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_prospecto', to='prospectos.prospecto', verbose_name='Prospecto (Cliente Nuevo)')),
                ('usuario_decision_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_decision_admin', to=settings.AUTH_USER_MODEL, verbose_name='Decisión Tomada por (Admin.)')),
                ('usuario_decision_cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_decision_cartera', to=settings.AUTH_USER_MODEL, verbose_name='Decisión Tomada por (Cartera)')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='vendedores.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_hora'],
                'unique_together': {('empresa', 'numero_pedido_empresa')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('tipo_detalle', models.CharField(choices=[('ENVIO', 'Producto Enviado'), ('DEVOLUCION', 'Producto Devuelto')], default='ENVIO', max_length=10, verbose_name='Tipo de Detalle')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario (IVA Incl.)')),
                ('verificado_bodega', models.BooleanField(default=False, verbose_name='Verificado Bodega')),
                ('cantidad_verificada', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Verificada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido', verbose_name='Pedido Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'unique_together': {('pedido', 'producto', 'tipo_detalle')},
            },
        ),
    ]
