# Generated by Django 5.2.1 on 2025-07-02 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        ('vendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Pedido')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION_CARTERA', 'Pendiente Aprobación Cartera'), ('RECHAZADO_CARTERA', 'Rechazado por Cartera'), ('PENDIENTE_APROBACION_ADMIN', 'Pendiente Aprobación Administración'), ('RECHAZADO_ADMIN', 'Rechazado por Administración'), ('APROBADO_ADMIN', 'Aprobado por Administración (Listo Bodega)'), ('PROCESANDO', 'Procesando en Bodega'), ('COMPLETADO', 'Completado en Bodega'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=35, verbose_name='Estado del Pedido')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Observaciones del Vendedor')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento Aplicado (%)')),
                ('token_descarga_fotos', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('motivo_cartera', models.TextField(blank=True, null=True, verbose_name='Motivo/Notas Cartera')),
                ('fecha_decision_cartera', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión Cartera')),
                ('motivo_admin', models.TextField(blank=True, null=True, verbose_name='Motivo/Notas Administración')),
                ('fecha_decision_admin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión Administración')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clientes.empresa', verbose_name='Empresa')),
                ('usuario_decision_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_decision_admin', to=settings.AUTH_USER_MODEL, verbose_name='Decisión Tomada por (Admin.)')),
                ('usuario_decision_cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_decision_cartera', to=settings.AUTH_USER_MODEL, verbose_name='Decisión Tomada por (Cartera)')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='vendedores.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario (IVA Incl.)')),
                ('verificado_bodega', models.BooleanField(default=False, verbose_name='Verificado Bodega')),
                ('cantidad_verificada', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Verificada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido', verbose_name='Pedido Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'unique_together': {('pedido', 'producto')},
            },
        ),
    ]
