# Generated by Django 5.2.1 on 2025-09-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='tipo_detalle',
            field=models.CharField(choices=[('VENTA', 'Venta Normal'), ('DEVOLUCION', 'Devolución en Cambio'), ('ENVIO', 'Envío en Cambio')], default='VENTA', max_length=20, verbose_name='Tipo de Detalle'),
        ),
    ]
