# Generated by Django 5.2.1 on 2025-05-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_descarga_fotos',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
