# Generated by Django 5.2.1 on 2025-10-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_detallepedido_tipo_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_hora'], 'permissions': [('can_view_financial_reports', 'Puede ver reportes financieros con subtotales')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
