# Generated by Django 5.2.1 on 2025-05-20 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_poblar_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_descarga_fotos',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
