# Generated by Django 5.2.1 on 2025-05-21 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_token_descarga_fotos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_decision_admin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión Administración'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_decision_cartera',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión Cartera'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo/Notas Administración'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cartera',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo/Notas Cartera'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_decision_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_decision_admin', to=settings.AUTH_USER_MODEL, verbose_name='Decisión Tomada por (Admin.)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_decision_cartera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_decision_cartera', to=settings.AUTH_USER_MODEL, verbose_name='Decisión Tomada por (Cartera)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION_CARTERA', 'Pendiente Aprobación Cartera'), ('RECHAZADO_CARTERA', 'Rechazado por Cartera'), ('PENDIENTE_APROBACION_ADMIN', 'Pendiente Aprobación Administración'), ('RECHAZADO_ADMIN', 'Rechazado por Administración'), ('APROBADO_ADMIN', 'Aprobado por Administración (Listo Bodega)'), ('PROCESANDO', 'Procesando en Bodega'), ('COMPLETADO', 'Completado en Bodega'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=35, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Vendedor'),
        ),
    ]
