# Generated by Django 5.2.1 on 2025-07-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_cliente_online_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar'), ('ONLINE', 'Online')], default='ESTANDAR', max_length=10, verbose_name='Tipo de Pedido'),
        ),
    ]
