# Generated by Django 5.2.1 on 2025-07-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_activo'),
        ('pedidos', '0006_pedido_tipo_pedido'),
        ('pedidos_online', '0002_alter_clienteonline_options_and_more'),
        ('prospectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_estandar', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_online_rel', to='pedidos_online.clienteonline', verbose_name='Cliente Online'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prospecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_prospecto', to='prospectos.prospecto', verbose_name='Prospecto (Cliente Nuevo)'),
        ),
    ]
