# Generated by Django 5.2.1 on 2025-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_cliente_alter_pedido_cliente_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('CONTADO', 'Contado'), ('ADDI', 'Addi'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('OTRO_ONLINE', 'Otro Pago Online')], default='CREDITO', max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
