# Generated by Django 5.2.1 on 2025-07-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_estado'),
        ('productos', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='tipo_detalle',
            field=models.CharField(choices=[('ENVIO', 'Producto Enviado'), ('DEVOLUCION', 'Producto Devuelto')], default='ENVIO', max_length=10, verbose_name='Tipo de Detalle'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'producto', 'tipo_detalle')},
        ),
    ]
