# Generated by Django 5.2.1 on 2025-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_detallepedido_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mostrar_precios_pdf',
            field=models.BooleanField(default=True, verbose_name='Mostrar Precios en PDF'),
        ),
    ]
