# Generated by Django 5.2.1 on 2025-07-07 06:18

import django.db.models.deletion
import django.utils.timezone
import recaudos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_empresa_ciudad_empresa_correo_electronico_and_more'),
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consignacion', models.DateField(help_text='Fecha en que se realizó el depósito en el banco.')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total que figura en el comprobante de depósito.', max_digits=15)),
                ('numero_referencia', models.CharField(help_text='Número de la transacción o referencia del depósito.', max_length=100)),
                ('comprobante_adjunto', models.FileField(help_text='Foto o PDF del recibo de consignación.', upload_to=recaudos.models.ruta_comprobante_consignacion)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('VERIFICADA', 'Verificada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('notas_verificacion', models.TextField(blank=True, help_text="Notas del administrador al verificar o rechazar (ej: 'El valor no coincide').")),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignaciones', to='clientes.empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignaciones_realizadas', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'Consignación',
                'verbose_name_plural': 'Consignaciones',
                'ordering': ['-fecha_consignacion'],
            },
        ),
        migrations.CreateModel(
            name='Recaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_recibido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_recaudo', models.DateTimeField(default=django.utils.timezone.now)),
                ('concepto', models.TextField(blank=True, help_text='Ej: Abono a factura F-123, F-124. Pago total remisión R-55.')),
                ('estado', models.CharField(choices=[('EN_MANOS', 'En Manos del Vendedor'), ('DEPOSITADO', 'Depositado (Pend. Verificar)'), ('VERIFICADO', 'Verificado y Cerrado')], db_index=True, default='EN_MANOS', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='clientes.cliente')),
                ('consignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaudos_incluidos', to='recaudos.consignacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recaudos', to='clientes.empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recaudos_realizados', to='vendedores.vendedor')),
            ],
            options={
                'verbose_name': 'Recaudo de Dinero',
                'verbose_name_plural': 'Recaudos de Dinero',
                'ordering': ['-fecha_recaudo'],
            },
        ),
    ]
