# Generated by Django 5.2.1 on 2025-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosInformes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_placeholder', models.CharField(default='P', max_length=1, unique=True)),
            ],
            options={
                'verbose_name': 'Permiso de Informe',
                'verbose_name_plural': 'Permisos de Informes',
                'permissions': [('view_reporte_ventas_general', 'Puede ver el informe de ventas general'), ('view_reporte_ventas_vendedor', 'Puede ver el informe de ventas por vendedor'), ('view_informe_ingresos_bodega', 'Puede ver el informe de ingresos a bodega'), ('view_pedidos_aprobados', 'Puede ver el informe de pedidos aprobados'), ('view_pedidos_rechazados', 'Puede ver el informe de pedidos rechazados'), ('view_informe_devoluciones', 'Puede ver el informe de devoluciones de clientes'), ('view_comprobantes_despacho', 'Puede ver el informe de comprobantes de despacho'), ('view_total_pedidos', 'Puede ver el informe total de pedidos')],
            },
        ),
    ]
