# Generated by Django 5.2.1 on 2026-09-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisosinformes',
            options={'permissions': [('view_reporte_ventas_general', 'Puede ver el informe de ventas general'), ('view_reporte_ventas_vendedor', 'Puede ver el informe de ventas por vendedor'), ('view_informe_ingresos_bodega', 'Puede ver el informe de ingresos a bodega'), ('view_pedidos_aprobados', 'Puede ver el informe de pedidos aprobados'), ('view_pedidos_aprobados_cartera', 'Puede ver el informe de pedidos aprobados por cartera'), ('view_pedidos_rechazados', 'Puede ver el informe de pedidos rechazados'), ('view_informe_devoluciones', 'Puede ver el informe de devoluciones de clientes'), ('view_comprobantes_despacho', 'Puede ver el informe de comprobantes de despacho'), ('view_total_pedidos', 'Puede ver el informe total de pedidos')], 'verbose_name': 'Permiso de Informe', 'verbose_name_plural': 'Permisos de Informes'},
        ),
    ]
