# Generated by Django 5.2.1 on 2025-05-17 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_facturacion', models.CharField(choices=[('PENDIENTE_FACTURAR', 'Pendiente por Facturar'), ('FACTURADO', 'Facturado'), ('ANULADO', 'Factura Anulada')], default='PENDIENTE_FACTURAR', max_length=25, verbose_name='Estado de Facturación')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Factura/Documento')),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Facturación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales de Facturación')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_factura', to='pedidos.pedido', verbose_name='Pedido Asociado')),
                ('usuario_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_gestionadas_%(app_label)s', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Acción Factura)')),
            ],
            options={
                'verbose_name': 'Registro de Facturación',
                'verbose_name_plural': 'Registros de Facturación',
                'ordering': ['-pedido__fecha_hora'],
            },
        ),
    ]
