# Generated by Django 5.2.1 on 2025-09-24 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0002_initial'),
        ('clientes', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFacturaDespacho',
            fields=[
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='estado_facturacion_info', serialize=False, to='bodega.comprobantedespacho', verbose_name='Comprobante de Despacho Asociado')),
                ('estado', models.CharField(choices=[('POR_FACTURAR', 'Por Facturar'), ('FACTURADO', 'Facturado')], db_index=True, default='POR_FACTURAR', max_length=20, verbose_name='Estado de Facturación')),
                ('fecha_hora_facturado_sistema', models.DateTimeField(blank=True, help_text='Fecha y hora en que se actualizó el estado a FACTURADO en esta aplicación.', null=True, verbose_name='Fecha/Hora Marcado como Facturado (Sistema)')),
                ('referencia_factura_externa', models.CharField(blank=True, help_text='Número o ID de la factura en el sistema contable externo.', max_length=100, null=True, verbose_name='Referencia Factura Externa')),
                ('notas_facturacion', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales de Facturación')),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_factura_despachos', to='clientes.empresa')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_facturados_gestionados_por_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable (Facturación)')),
            ],
            options={
                'verbose_name': 'Estado de Facturación de Despacho',
                'verbose_name_plural': 'Estados de Facturación de Despachos',
                'ordering': ['empresa', 'despacho__fecha_hora_despacho'],
                'permissions': [('view_despachos_a_facturar', 'Puede ver lista de despachos por facturar'), ('can_mark_despacho_facturado', 'Puede marcar un despacho como facturado'), ('view_informe_facturados_fecha', 'Puede ver informe de facturados por fecha'), ('view_informe_despachos_cliente', 'Puede ver informe de despachos por cliente (factura)'), ('view_informe_despachos_estado', 'Puede ver informe de despachos por estado (factura)'), ('view_informe_despachos_pedido', 'Puede ver informe de despachos por pedido (factura)')],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_facturacion', models.CharField(choices=[('PENDIENTE_FACTURAR', 'Pendiente por Facturar'), ('FACTURADO', 'Facturado'), ('ANULADO', 'Factura Anulada')], default='PENDIENTE_FACTURAR', max_length=25, verbose_name='Estado de Facturación')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Factura/Documento')),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Facturación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales de Facturación')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clientes.empresa')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_factura', to='pedidos.pedido', verbose_name='Pedido Asociado')),
                ('usuario_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_gestionadas_%(app_label)s_factura_model', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Acción Factura)')),
            ],
            options={
                'verbose_name': 'Registro de Facturación de Pedido',
                'verbose_name_plural': 'Registros de Facturación de Pedidos',
                'ordering': ['-pedido__fecha_hora'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'pedido'), name='factura_unica_por_empresa_pedido')],
            },
        ),
    ]
