# Generated by Django 5.2.1 on 2025-05-18 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_comprobantedespacho_detallecomprobantedespacho'),
        ('factura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFacturaDespacho',
            fields=[
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='estado_facturacion_info', serialize=False, to='bodega.comprobantedespacho', verbose_name='Comprobante de Despacho Asociado')),
                ('estado', models.CharField(choices=[('POR_FACTURAR', 'Por Facturar'), ('FACTURADO', 'Facturado')], db_index=True, default='POR_FACTURAR', max_length=20, verbose_name='Estado de Facturación')),
                ('fecha_hora_facturado_sistema', models.DateTimeField(blank=True, help_text='Fecha y hora en que se actualizó el estado a FACTURADO en esta aplicación.', null=True, verbose_name='Fecha/Hora Marcado como Facturado (Sistema)')),
                ('referencia_factura_externa', models.CharField(blank=True, help_text='Número o ID de la factura en el sistema contable externo.', max_length=100, null=True, verbose_name='Referencia Factura Externa')),
                ('notas_facturacion', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales de Facturación')),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_facturados_gestionados_por_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable (Facturación)')),
            ],
            options={
                'verbose_name': 'Estado de Facturación de Despacho',
                'verbose_name_plural': 'Estados de Facturación de Despachos',
                'ordering': ['despacho__fecha_hora_despacho'],
            },
        ),
    ]
