# Generated by Django 5.2.1 on 2025-09-24 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_factura', to='pedidos.pedido', verbose_name='Pedido Asociado'),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario_accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_gestionadas_%(app_label)s_factura_model', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Acción Factura)'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.UniqueConstraint(fields=('empresa', 'pedido'), name='factura_unica_por_empresa_pedido'),
        ),
    ]
