# Generated by Django 5.2.1 on 2025-05-25 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_estadofacturadespacho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadofacturadespacho',
            options={'ordering': ['despacho__fecha_hora_despacho'], 'permissions': [('view_despachos_a_facturar', 'Puede ver lista de despachos por facturar'), ('can_mark_despacho_facturado', 'Puede marcar un despacho como facturado'), ('view_informe_facturados_fecha', 'Puede ver informe de facturados por fecha'), ('view_informe_despachos_cliente', 'Puede ver informe de despachos por cliente (factura)'), ('view_informe_despachos_estado', 'Puede ver informe de despachos por estado (factura)'), ('view_informe_despachos_pedido', 'Puede ver informe de despachos por pedido (factura)')], 'verbose_name': 'Estado de Facturación de Despacho', 'verbose_name_plural': 'Estados de Facturación de Despachos'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-pedido__fecha_hora'], 'verbose_name': 'Registro de Facturación de Pedido', 'verbose_name_plural': 'Registros de Facturación de Pedidos'},
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario_accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_gestionadas_%(app_label)s_factura_model', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Acción Factura)'),
        ),
    ]
