# Generated by Django 5.2.1 on 2025-09-24 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Efectiva del Conteo')),
                ('motivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo del Conteo')),
                ('revisado_con', models.CharField(blank=True, max_length=150, null=True, verbose_name='Revisado Con')),
                ('notas_generales', models.TextField(blank=True, null=True, verbose_name='Notas Generales')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cabecera de Conteo de Inventario',
                'verbose_name_plural': 'Cabeceras de Conteos de Inventario',
                'ordering': ['-fecha_hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_despacho', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Despacho')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Despacho')),
                ('es_parcial', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comprobante de Despacho',
                'verbose_name_plural': 'Comprobantes de Despacho',
                'ordering': ['-fecha_hora_despacho'],
            },
        ),
        migrations.CreateModel(
            name='ConteoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema_antes', models.IntegerField(verbose_name='Cantidad en Sistema (Antes del Conteo)')),
                ('cantidad_fisica_contada', models.IntegerField(verbose_name='Cantidad Física Contada')),
                ('fecha_conteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Conteo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Ítem Específico')),
            ],
            options={
                'verbose_name': 'Detalle de Conteo de Inventario',
                'verbose_name_plural': 'Detalles de Conteos de Inventario',
                'ordering': ['cabecera_conteo', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='DetalleBorradorDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_escaneada_en_borrador', models.PositiveIntegerField(default=0, verbose_name='Cantidad Escaneada en Borrador')),
            ],
            options={
                'verbose_name': 'Detalle de Borrador de Despacho',
                'verbose_name_plural': 'Detalles de Borrador de Despacho',
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobanteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField(verbose_name='Cantidad Despachada en este Comprobante')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante de Despacho',
                'verbose_name_plural': 'Detalles de Comprobantes de Despacho',
            },
        ),
        migrations.CreateModel(
            name='DetalleIngresoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario (Opcional)')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso a Bodega',
                'verbose_name_plural': 'Detalles de Ingreso a Bodega',
            },
        ),
        migrations.CreateModel(
            name='IngresoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora Ingreso')),
                ('proveedor_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Información Proveedor/Origen')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia (Factura Compra, Remisión, etc.)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Ingreso a Bodega',
                'verbose_name_plural': 'Ingresos a Bodega',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Movida')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_DEVOLUCION_CLIENTE', 'Entrada por Devolución de Cliente'), ('SALIDA_VENTA_PENDIENTE', 'Salida por Venta (Pendiente Aprob)'), ('SALIDA_VENTA_APROBADA', 'Salida por Venta (Aprobada)'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_OTRO', 'Salida por Otro Motivo'), ('ENTRADA_OTRO', 'Entrada por Otro Motivo'), ('ENTRADA_RECHAZO_CARTERA', 'Entrada por Rechazo Pedido Cartera'), ('ENTRADA_RECHAZO_ADMIN', 'Entrada por Rechazo Pedido Admin'), ('SALIDA_MUESTRARIO', 'Salida para Muestrario'), ('SALIDA_EXHIBIDOR', 'Salida para Exhibidor'), ('SALIDA_TRASLADO', 'Salida por Traslado Interno'), ('SALIDA_PRESTAMO', 'Salida por Préstamo'), ('SALIDA_DONACION_BAJA', 'Salida por Donación/Baja'), ('SALIDA_INTERNA_OTRA', 'Salida Interna (Otra)'), ('ENTRADA_DEV_MUESTRARIO', 'Devolución de Muestrario'), ('ENTRADA_DEV_EXHIBIDOR', 'Devolución de Exhibidor'), ('ENTRADA_DEV_TRASLADO', 'Devolución de Traslado Interno'), ('ENTRADA_DEV_PRESTAMO', 'Devolución de Préstamo'), ('ENTRADA_DEV_INTERNA_OTRA', 'Devolución Interna (Otra)'), ('ENTRADA_CAMBIO', 'Entrada por Cambio de Cliente'), ('SALIDA_CAMBIO', 'Salida por Cambio de Cliente')], max_length=35, verbose_name='Tipo de Movimiento')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia (ID Pedido, Factura, etc.)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_hora', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(blank=True, help_text='ID interno o código del empleado de bodega', max_length=50, null=True, unique=True)),
                ('area_asignada', models.CharField(blank=True, help_text='Área específica de la bodega asignada', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el perfil de bodega está activo')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaInternaCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_salida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Salida')),
                ('tipo_salida', models.CharField(choices=[('MUESTRARIO', 'Muestrario para Vendedor'), ('EXHIBIDOR', 'Para Exhibidor/Punto de Venta'), ('TRASLADO_INTERNO', 'Traslado Interno entre Almacenes/Bodegas'), ('PRESTAMO', 'Préstamo Temporal'), ('DONACION_BAJA', 'Donación o Baja de Inventario'), ('OTRO', 'Otro Tipo de Salida Interna')], max_length=20, verbose_name='Tipo de Salida')),
                ('destino_descripcion', models.CharField(help_text='Ej: Vendedor Juan Pérez, Tienda Centro, Evento XYZ', max_length=255, verbose_name='Destino / Entregado A')),
                ('documento_referencia_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Referencia Externo (Opcional)')),
                ('estado', models.CharField(choices=[('DESPACHADA', 'Despachada (Pendiente Devolución)'), ('DEVUELTA_PARCIAL', 'Devuelta Parcialmente'), ('DEVUELTA_TOTAL', 'Devuelta Totalmente'), ('CERRADA', 'Cerrada (No requiere devolución, ej. baja)')], default='DESPACHADA', max_length=20, verbose_name='Estado de la Salida')),
                ('fecha_prevista_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Prevista Devolución (si aplica)')),
                ('observaciones_salida', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales de la Salida')),
            ],
            options={
                'verbose_name': 'Salida Interna (Cabecera)',
                'verbose_name_plural': 'Salidas Internas (Cabeceras)',
                'ordering': ['-fecha_hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInternaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField(verbose_name='Cantidad Despachada')),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0, verbose_name='Cantidad Devuelta')),
                ('observaciones_detalle', models.TextField(blank=True, null=True, verbose_name='Observaciones del Ítem')),
            ],
            options={
                'verbose_name': 'Detalle de Salida Interna',
                'verbose_name_plural': 'Detalles de Salidas Internas',
                'permissions': [('view_lista_pedidos_bodega', 'Puede ver la lista de pedidos para bodega')],
            },
        ),
        migrations.CreateModel(
            name='BorradorDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora Creación')),
                ('fecha_hora_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Borrador de Despacho',
                'verbose_name_plural': 'Borradores de Despacho',
            },
        ),
    ]
