# Generated by Django 5.2.1 on 2025-05-17 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Efectiva del Conteo')),
                ('motivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo del Conteo')),
                ('revisado_con', models.CharField(blank=True, max_length=150, null=True, verbose_name='Revisado Con')),
                ('notas_generales', models.TextField(blank=True, null=True, verbose_name='Notas Generales')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Cabecera de Conteo de Inventario',
                'verbose_name_plural': 'Cabeceras de Conteos de Inventario',
                'ordering': ['-fecha_hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='ConteoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conteo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Conteo')),
                ('cantidad_sistema_antes', models.IntegerField(verbose_name='Cantidad en Sistema (Antes del Conteo)')),
                ('cantidad_fisica_contada', models.IntegerField(verbose_name='Cantidad Física Contada')),
                ('fecha_actualizacion_stock', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Efectiva del Ajuste')),
                ('motivo_conteo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo del Conteo/Ajuste')),
                ('revisado_con', models.CharField(blank=True, max_length=150, null=True, verbose_name='Revisado/Contado Con')),
                ('notas_generales', models.TextField(blank=True, null=True, verbose_name='Notas Generales del Conteo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('cabecera_conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_conteo', to='bodega.cabeceraconteo', verbose_name='Cabecera del Conteo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_inventario', to='productos.producto', verbose_name='Producto Contado')),
                ('usuario_conteo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Contó')),
            ],
            options={
                'verbose_name': 'Detalle de Conteo de Inventario',
                'verbose_name_plural': 'Detalles de Conteos de Inventario',
                'ordering': ['cabecera_conteo', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='IngresoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora Ingreso')),
                ('proveedor_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Información Proveedor/Origen')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia (Factura Compra, Remisión, etc.)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Ingreso a Bodega',
                'verbose_name_plural': 'Ingresos a Bodega',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Movida')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_DEVOLUCION', 'Entrada por Devolución'), ('SALIDA_VENTA', 'Salida por Venta'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_DEVOLUCION', 'Salida por Devolución'), ('SALIDA_OTRO', 'Salida por Otro Motivo'), ('ENTRADA_OTRO', 'Entrada por Otro Motivo')], max_length=25, verbose_name='Tipo de Movimiento')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento Referencia (ID Pedido, Factura, etc.)')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_hora', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(blank=True, help_text='ID interno o código del empleado de bodega', max_length=50, null=True, unique=True)),
                ('area_asignada', models.CharField(blank=True, help_text='Área específica de la bodega asignada', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el perfil de bodega está activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_bodega', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngresoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario Ingreso (Opcional)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ingreso', to='productos.producto', verbose_name='Producto Ingresado')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.ingresobodega', verbose_name='Ingreso Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso a Bodega',
                'verbose_name_plural': 'Detalles de Ingreso a Bodega',
                'unique_together': {('ingreso', 'producto')},
            },
        ),
    ]
