# Generated by Django 5.2.1 on 2025-07-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
        ('clientes', '0002_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabeceraconteo',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteos_inventario', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='conteoinventario',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_conteo_inventario', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='salidainternacabecera',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_internas', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='conteoinventario',
            name='cabecera_conteo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_conteo', to='bodega.cabeceraconteo', verbose_name='Cabecera del Conteo'),
        ),
    ]
