# Generated by Django 5.2.1 on 2025-07-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteoinventario',
            name='fecha_actualizacion_stock',
        ),
        migrations.RemoveField(
            model_name='conteoinventario',
            name='motivo_conteo',
        ),
        migrations.RemoveField(
            model_name='conteoinventario',
            name='notas_generales',
        ),
        migrations.RemoveField(
            model_name='conteoinventario',
            name='revisado_con',
        ),
        migrations.AlterField(
            model_name='conteoinventario',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Ítem Específico'),
        ),
    ]
