# Generated by Django 5.2.1 on 2025-05-18 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_despacho', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Despacho')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del Despacho')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_despacho', to='pedidos.pedido', verbose_name='Pedido Asociado')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_despachados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable (Bodega)')),
            ],
            options={
                'verbose_name': 'Comprobante de Despacho',
                'verbose_name_plural': 'Comprobantes de Despacho',
                'ordering': ['-fecha_hora_despacho'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobanteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField(verbose_name='Cantidad Despachada en este Comprobante')),
                ('comprobante_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.comprobantedespacho', verbose_name='Comprobante de Despacho')),
                ('detalle_pedido_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_despachados', to='pedidos.detallepedido', verbose_name='Línea del Pedido Original')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_despachos', to='productos.producto', verbose_name='Producto Despachado')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante de Despacho',
                'verbose_name_plural': 'Detalles de Comprobantes de Despacho',
                'unique_together': {('comprobante_despacho', 'producto', 'detalle_pedido_origen')},
            },
        ),
    ]
