# Generated by Django 5.2.1 on 2025-05-22 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_comprobantedespacho_detallecomprobantedespacho'),
        ('productos', '0005_limpiar_fotos_huerfanas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_DEVOLUCION_CLIENTE', 'Entrada por Devolución de Cliente'), ('SALIDA_VENTA_PENDIENTE', 'Salida por Venta (Pendiente Aprob)'), ('SALIDA_VENTA_APROBADA', 'Salida por Venta (Aprobada)'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_OTRO', 'Salida por Otro Motivo'), ('ENTRADA_OTRO', 'Entrada por Otro Motivo'), ('ENTRADA_RECHAZO_CARTERA', 'Entrada por Rechazo Pedido Cartera'), ('ENTRADA_RECHAZO_ADMIN', 'Entrada por Rechazo Pedido Admin'), ('SALIDA_MUESTRARIO', 'Salida para Muestrario'), ('SALIDA_EXHIBIDOR', 'Salida para Exhibidor'), ('SALIDA_TRASLADO', 'Salida por Traslado Interno'), ('SALIDA_PRESTAMO', 'Salida por Préstamo'), ('SALIDA_DONACION_BAJA', 'Salida por Donación/Baja'), ('SALIDA_INTERNA_OTRA', 'Salida Interna (Otra)'), ('ENTRADA_DEV_MUESTRARIO', 'Devolución de Muestrario'), ('ENTRADA_DEV_EXHIBIDOR', 'Devolución de Exhibidor'), ('ENTRADA_DEV_TRASLADO', 'Devolución de Traslado Interno'), ('ENTRADA_DEV_PRESTAMO', 'Devolución de Préstamo'), ('ENTRADA_DEV_INTERNA_OTRA', 'Devolución Interna (Otra)')], max_length=35, verbose_name='Tipo de Movimiento'),
        ),
        migrations.CreateModel(
            name='SalidaInternaCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_salida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Salida')),
                ('tipo_salida', models.CharField(choices=[('MUESTRARIO', 'Muestrario para Vendedor'), ('EXHIBIDOR', 'Para Exhibidor/Punto de Venta'), ('TRASLADO_INTERNO', 'Traslado Interno entre Almacenes/Bodegas'), ('PRESTAMO', 'Préstamo Temporal'), ('DONACION_BAJA', 'Donación o Baja de Inventario'), ('OTRO', 'Otro Tipo de Salida Interna')], max_length=20, verbose_name='Tipo de Salida')),
                ('destino_descripcion', models.CharField(help_text='Ej: Vendedor Juan Pérez, Tienda Centro, Evento XYZ', max_length=255, verbose_name='Destino / Entregado A')),
                ('documento_referencia_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc. Referencia Externo (Opcional)')),
                ('estado', models.CharField(choices=[('DESPACHADA', 'Despachada (Pendiente Devolución)'), ('DEVUELTA_PARCIAL', 'Devuelta Parcialmente'), ('DEVUELTA_TOTAL', 'Devuelta Totalmente'), ('CERRADA', 'Cerrada (No requiere devolución, ej. baja)')], default='DESPACHADA', max_length=20, verbose_name='Estado de la Salida')),
                ('fecha_prevista_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Prevista Devolución (si aplica)')),
                ('observaciones_salida', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales de la Salida')),
                ('responsable_entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_internas_entregadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Entrega (Bodega)')),
            ],
            options={
                'verbose_name': 'Salida Interna (Cabecera)',
                'verbose_name_plural': 'Salidas Internas (Cabeceras)',
                'ordering': ['-fecha_hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='SalidaInternaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.PositiveIntegerField(verbose_name='Cantidad Despachada')),
                ('cantidad_devuelta', models.PositiveIntegerField(default=0, verbose_name='Cantidad Devuelta')),
                ('observaciones_detalle', models.TextField(blank=True, null=True, verbose_name='Observaciones del Ítem')),
                ('cabecera_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.salidainternacabecera', verbose_name='Cabecera de Salida Interna')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Salida Interna',
                'verbose_name_plural': 'Detalles de Salidas Internas',
                'unique_together': {('cabecera_salida', 'producto')},
            },
        ),
    ]
