# Generated by Django 5.2.1 on 2025-09-27 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_initial'),
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_DEVOLUCION_CLIENTE', 'Entrada por Devolución de Cliente'), ('SALIDA_VENTA_PENDIENTE', 'Salida por Venta (Pendiente Aprob)'), ('SALIDA_VENTA_APROBADA', 'Salida por Venta (Aprobada)'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_OTRO', 'Salida por Otro Motivo'), ('ENTRADA_OTRO', 'Entrada por Otro Motivo'), ('ENTRADA_RECHAZO_CARTERA', 'Entrada por Rechazo Pedido Cartera'), ('ENTRADA_RECHAZO_ADMIN', 'Entrada por Rechazo Pedido Admin'), ('SALIDA_MUESTRARIO', 'Salida para Muestrario'), ('SALIDA_EXHIBIDOR', 'Salida para Exhibidor'), ('SALIDA_TRASLADO', 'Salida por Traslado Interno'), ('SALIDA_PRESTAMO', 'Salida por Préstamo'), ('SALIDA_DONACION_BAJA', 'Salida por Donación/Baja'), ('SALIDA_INTERNA_OTRA', 'Salida Interna (Otra)'), ('ENTRADA_DEV_MUESTRARIO', 'Devolución de Muestrario'), ('ENTRADA_DEV_EXHIBIDOR', 'Devolución de Exhibidor'), ('ENTRADA_DEV_TRASLADO', 'Devolución de Traslado Interno'), ('ENTRADA_DEV_PRESTAMO', 'Devolución de Préstamo'), ('ENTRADA_DEV_INTERNA_OTRA', 'Devolución Interna (Otra)'), ('ENTRADA_CAMBIO', 'Entrada por Cambio de Producto'), ('SALIDA_CAMBIO', 'Salida por Cambio de Producto'), ('ENTRADA_CAMBIO', 'Entrada por Cambio de Cliente'), ('SALIDA_CAMBIO', 'Salida por Cambio de Cliente')], max_length=35, verbose_name='Tipo de Movimiento'),
        ),
        migrations.CreateModel(
            name='CambioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Cambio')),
                ('cantidad_entrante', models.PositiveIntegerField(default=1, verbose_name='Cantidad que Entra')),
                ('cantidad_saliente', models.PositiveIntegerField(default=1, verbose_name='Cantidad que Sale')),
                ('motivo', models.TextField(help_text='Ej: Cambio de talla, defecto de fábrica, etc.', verbose_name='Motivo del Cambio')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Referencia (Opcional)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_producto', to='clientes.empresa')),
                ('producto_entrante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_recibidos', to='productos.producto', verbose_name='Producto que Entra')),
                ('producto_saliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_entregados', to='productos.producto', verbose_name='Producto que Sale')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Cambio de Producto',
                'verbose_name_plural': 'Cambios de Productos',
                'ordering': ['-fecha_hora'],
                'permissions': [('can_manage_product_changes', 'Puede gestionar cambios de productos')],
            },
        ),
    ]
