# Generated by Django 5.2.1 on 2025-05-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_alter_movimientoinventario_tipo_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salidainternadetalle',
            options={'permissions': [('view_lista_pedidos_bodega', 'Puede ver la lista de pedidos para bodega')], 'verbose_name': 'Detalle de Salida Interna', 'verbose_name_plural': 'Detalles de Salidas Internas'},
        ),
    ]
