# Generated by Django 5.2.1 on 2025-07-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_alter_movimientoinventario_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantedespacho',
            name='es_parcial',
            field=models.BooleanField(default=False, help_text='Indica si este comprobante corresponde a un despacho parcial.'),
        ),
    ]
