# Generated by Django 5.2.1 on 2025-07-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_comprobantedespacho_es_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantedespacho',
            name='es_parcial',
            field=models.BooleanField(default=True),
        ),
    ]
