# Generated by Django 5.2.1 on 2025-07-27 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_alter_comprobantedespacho_es_parcial'),
        ('clientes', '0004_cliente_activo'),
        ('pedidos', '0011_alter_detallepedido_unique_together_and_more'),
        ('productos', '0003_alter_producto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora Creación')),
                ('fecha_hora_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa', verbose_name='Empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borradores_despacho', to='pedidos.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Borrador de Despacho',
                'verbose_name_plural': 'Borradores de Despacho',
                'unique_together': {('pedido', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='DetalleBorradorDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_escaneada_en_borrador', models.PositiveIntegerField(default=0, verbose_name='Cantidad Escaneada en Borrador')),
                ('borrador_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_borrador', to='bodega.borradordespacho', verbose_name='Borrador de Despacho')),
                ('detalle_pedido_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_borrador_asociados', to='pedidos.detallepedido', verbose_name='Detalle Pedido Original')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Borrador de Despacho',
                'verbose_name_plural': 'Detalles de Borrador de Despacho',
                'unique_together': {('borrador_despacho', 'detalle_pedido_origen')},
            },
        ),
    ]
