# Generated by Django 5.2.1 on 2026-03-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_alter_movimientoinventario_tipo_movimiento_and_more'),
        ('clientes', '0003_remove_empresa_tallas_dama_display_and_more'),
        ('productos', '0003_alter_producto_genero'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientoinventario',
            unique_together={('empresa', 'documento_referencia', 'tipo_movimiento', 'producto')},
        ),
    ]
