# Generated by Django 5.2.1 on 2026-07-15 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_alter_movimientoinventario_unique_together'),
        ('clientes', '0005_empresa_usa_shopify'),
        ('productos', '0007_alter_producto_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalbodega',
            options={'ordering': ['user__username'], 'verbose_name': 'Personal de Bodega', 'verbose_name_plural': 'Personal de Bodega'},
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_DEVOLUCION_CLIENTE', 'Entrada por Devolución de Cliente'), ('ENTRADA_CANCELACION', 'Entrada por Cancelación de Pedido'), ('ENTRADA_CANCELACION_INGRESO', 'Entrada por Cancelación de Ingreso'), ('SALIDA_VENTA_PENDIENTE', 'Salida por Venta (Pendiente Aprob)'), ('SALIDA_VENTA_APROBADA', 'Salida por Venta (Aprobada)'), ('SALIDA_VENTA_ALMACEN', 'Salida por Venta en Almacén (Desktop)'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_CANCELACION', 'Salida por Cancelación'), ('ENTRADA_PRODUCCION', 'Entrada desde Producción'), ('SALIDA_OTRO', 'Salida por Otro Motivo'), ('ENTRADA_OTRO', 'Entrada por Otro Motivo'), ('ENTRADA_RECHAZO_CARTERA', 'Entrada por Rechazo Pedido Cartera'), ('ENTRADA_RECHAZO_ADMIN', 'Entrada por Rechazo Pedido Admin'), ('SALIDA_MUESTRARIO', 'Salida para Muestrario'), ('SALIDA_EXHIBIDOR', 'Salida para Exhibidor'), ('SALIDA_TRASLADO', 'Salida por Traslado entre Bodegas'), ('ENTRADA_TRASLADO', 'Entrada por Traslado entre Bodegas'), ('SALIDA_PRESTAMO', 'Salida por Préstamo'), ('SALIDA_DONACION_BAJA', 'Salida por Donación/Baja'), ('SALIDA_INTERNA_OTRA', 'Salida Interna (Otra)'), ('ENTRADA_DEV_MUESTRARIO', 'Devolución de Muestrario'), ('ENTRADA_DEV_EXHIBIDOR', 'Devolución de Exhibidor'), ('ENTRADA_DEV_TRASLADO', 'Devolución de Traslado Interno'), ('ENTRADA_DEV_PRESTAMO', 'Devolución de Préstamo'), ('ENTRADA_DEV_INTERNA_OTRA', 'Devolución Interna (Otra)'), ('ENTRADA_CAMBIO', 'Entrada por Cambio de Producto'), ('SALIDA_CAMBIO', 'Salida por Cambio de Producto')], max_length=35, verbose_name='Tipo de Movimiento'),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SALDOS', 'Saldos y Colas'), ('PUNTO_VENTA', 'Punto de Venta'), ('MUESTRARIO', 'Muestrario'), ('TRANSITO', 'Tránsito'), ('OTRA', 'Otra')], default='OTRA', max_length=20, verbose_name='Tipo de Bodega')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es la Bodega Principal')),
                ('activa', models.BooleanField(default=True, help_text='Si está desmarcada, no admite movimientos nuevos, pero conserva el histórico.', verbose_name='Activa')),
                ('requiere_confirmacion_recepcion', models.BooleanField(default=False, help_text="Si está marcado, los traslados hacia esta bodega quedan 'En Tránsito' hasta que alguien confirme la recepción.", verbose_name='Requiere Confirmación de Recepción')),
                ('disponible_venta_estandar', models.BooleanField(default=True, help_text='Vendedores del canal estándar pueden vender/ver este stock por defecto.', verbose_name='Disponible para Venta (Estándar)')),
                ('disponible_venta_online', models.BooleanField(default=True, help_text='Vendedores del canal online pueden vender/ver este stock por defecto.', verbose_name='Disponible para Venta (Online)')),
                ('disponible_venta_web', models.BooleanField(default=True, help_text='El canal Web/Shopify puede vender este stock por defecto.', verbose_name='Disponible para Venta (Web/Shopify)')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='clientes.empresa', verbose_name='Empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AccesoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('NINGUNO', 'Ninguno (bloqueado explícitamente)'), ('CONSULTA', 'Consulta'), ('OPERACION', 'Operación'), ('ADMIN', 'Administración')], default='OPERACION', max_length=20, verbose_name='Nivel de Acceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_bodega', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='bodega.bodega', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Acceso a Bodega',
                'verbose_name_plural': 'Accesos a Bodegas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='movimientoinventario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cabeceraconteo',
            name='bodega',
            field=models.ForeignKey(blank=True, help_text='Vacío = conteo general (todas las bodegas de la empresa).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='bodega.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='ingresobodega',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='bodega.bodega', verbose_name='Bodega Destino'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bodega.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='salidainternacabecera',
            name='bodega_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_internas_origen', to='bodega.bodega', verbose_name='Bodega de Origen'),
        ),
        migrations.AlterUniqueTogether(
            name='movimientoinventario',
            unique_together={('empresa', 'documento_referencia', 'tipo_movimiento', 'producto', 'bodega')},
        ),
        migrations.CreateModel(
            name='TrasladoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDO', 'Recibido'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Referencia')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Envío')),
                ('fecha_hora_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora de Recepción')),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrantes', to='bodega.bodega', verbose_name='Bodega de Destino')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salientes', to='bodega.bodega', verbose_name='Bodega de Origen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_bodega', to='clientes.empresa', verbose_name='Empresa')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('usuario_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
                ('usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Recibido Por')),
            ],
            options={
                'verbose_name': 'Traslado entre Bodegas',
                'verbose_name_plural': 'Traslados entre Bodegas',
                'ordering': ['-fecha_hora_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTrasladoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_traslados', to='productos.producto', verbose_name='Producto')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.trasladobodega', verbose_name='Traslado')),
            ],
            options={
                'verbose_name': 'Detalle de Traslado',
                'verbose_name_plural': 'Detalles de Traslado',
            },
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('empresa',), name='unica_bodega_principal_por_empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='bodega',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='accesobodega',
            unique_together={('usuario', 'bodega')},
        ),
        migrations.AlterUniqueTogether(
            name='detalletrasladobodega',
            unique_together={('traslado', 'producto')},
        ),
    ]
