# Generated by Django 5.2.1 on 2026-07-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_backfill_bodega_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresobodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='bodega.bodega', verbose_name='Bodega Destino'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bodega.bodega', verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='salidainternacabecera',
            name='bodega_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_internas_origen', to='bodega.bodega', verbose_name='Bodega de Origen'),
        ),
    ]
