# Generated by Django 5.2.1 on 2026-07-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0010_bodega_disponible_venta_puntoventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada por Compra'), ('ENTRADA_AJUSTE', 'Entrada por Ajuste'), ('ENTRADA_DEVOLUCION_CLIENTE', 'Entrada por Devolución de Cliente'), ('ENTRADA_CANCELACION', 'Entrada por Cancelación de Pedido'), ('ENTRADA_CANCELACION_INGRESO', 'Entrada por Cancelación de Ingreso'), ('SALIDA_VENTA_PENDIENTE', 'Salida por Venta (Pendiente Aprob)'), ('SALIDA_VENTA_APROBADA', 'Salida por Venta (Aprobada)'), ('SALIDA_VENTA_POS', 'Salida por Venta en Punto de Venta'), ('SALIDA_AJUSTE', 'Salida por Ajuste'), ('SALIDA_CANCELACION', 'Salida por Cancelación'), ('ENTRADA_PRODUCCION', 'Entrada desde Producción'), ('SALIDA_OTRO', 'Salida por Otro Motivo'), ('ENTRADA_OTRO', 'Entrada por Otro Motivo'), ('ENTRADA_RECHAZO_CARTERA', 'Entrada por Rechazo Pedido Cartera'), ('ENTRADA_RECHAZO_ADMIN', 'Entrada por Rechazo Pedido Admin'), ('SALIDA_MUESTRARIO', 'Salida para Muestrario'), ('SALIDA_EXHIBIDOR', 'Salida para Exhibidor'), ('SALIDA_TRASLADO', 'Salida por Traslado entre Bodegas'), ('ENTRADA_TRASLADO', 'Entrada por Traslado entre Bodegas'), ('SALIDA_PRESTAMO', 'Salida por Préstamo'), ('SALIDA_DONACION_BAJA', 'Salida por Donación/Baja'), ('SALIDA_INTERNA_OTRA', 'Salida Interna (Otra)'), ('ENTRADA_DEV_MUESTRARIO', 'Devolución de Muestrario'), ('ENTRADA_DEV_EXHIBIDOR', 'Devolución de Exhibidor'), ('ENTRADA_DEV_TRASLADO', 'Devolución de Traslado Interno'), ('ENTRADA_DEV_PRESTAMO', 'Devolución de Préstamo'), ('ENTRADA_DEV_INTERNA_OTRA', 'Devolución Interna (Otra)'), ('ENTRADA_CAMBIO', 'Entrada por Cambio de Producto'), ('SALIDA_CAMBIO', 'Salida por Cambio de Producto'), ('ENTRADA_DEVOLUCION_POS', 'Entrada por Devolución en Punto de Venta'), ('SALIDA_CAMBIO_POS', 'Salida por Cambio de Producto en Punto de Venta')], max_length=35, verbose_name='Tipo de Movimiento'),
        ),
    ]
