# Generated by Django 5.2.1 on 2026-07-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0011_alter_movimientoinventario_tipo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladobodega',
            name='numero_traslado_empresa',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Número de Traslado por Empresa'),
        ),
        migrations.AlterField(
            model_name='trasladobodega',
            name='documento_referencia',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Documento de Referencia'),
        ),
    ]
