# Generated by Django 5.2.1 on 2026-07-17 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0012_trasladobodega_numero_traslado_empresa_and_more'),
        ('clientes', '0010_empresa_shopify_sync_accion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trasladobodega',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_traslado_empresa__isnull', False)), fields=('empresa', 'numero_traslado_empresa'), name='numero_traslado_unico_por_empresa'),
        ),
    ]
