# Generated by Django 5.2.1 on 2025-09-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('tipo_cliente', models.CharField(choices=[('DETAL', 'Al Detal'), ('MAYOR', 'Al por Mayor')], default='DETAL', max_length=10, verbose_name='Tipo de Cliente')),
                ('forma_pago_preferida', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('ONLINE', 'Pago Online')], default='CONTADO', max_length=10, verbose_name='Forma de Pago Preferida')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_online', to='clientes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente Online',
                'verbose_name_plural': 'Clientes Online',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='PrecioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('DETAL', 'Al Detal'), ('MAYOR', 'Al por Mayor')], max_length=10, verbose_name='Tipo de Cliente')),
                ('precio_especial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Especial')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Promoción')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de Promoción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Precio Especial',
                'verbose_name_plural': 'Precios Especiales',
                'unique_together': {('producto', 'tipo_cliente')},
            },
        ),
    ]
