# Generated by Django 5.2.1 on 2025-07-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_activo'),
        ('productos', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('tipo_cliente', models.CharField(choices=[('DETAL', 'Al Detal'), ('MAYOR', 'Al por Mayor')], default='DETAL', max_length=10)),
                ('forma_pago_preferida', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('ONLINE', 'Pago Online')], default='CONTADO', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_online', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Cliente Online',
                'verbose_name_plural': 'Clientes Online',
            },
        ),
        migrations.CreateModel(
            name='PrecioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('DETAL', 'Al Detal'), ('MAYOR', 'Al por Mayor')], max_length=10)),
                ('precio_especial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Precio Especial',
                'verbose_name_plural': 'Precios Especiales',
                'unique_together': {('producto', 'tipo_cliente')},
            },
        ),
    ]
