# Generated by Django 5.2.1 on 2026-07-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_usa_shopify'),
        ('pedidos_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteonline',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_online', to='clientes.ciudad', verbose_name='Ciudad'),
        ),
    ]
