# Generated by Django 5.2.1 on 2025-07-23 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_activo'),
        ('pedidos_online', '0001_initial'),
        ('productos', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteonline',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Cliente Online', 'verbose_name_plural': 'Clientes Online'},
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_online', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='forma_pago_preferida',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('ONLINE', 'Pago Online')], default='CONTADO', max_length=10, verbose_name='Forma de Pago Preferida'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='nombre_completo',
            field=models.CharField(max_length=255, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='clienteonline',
            name='tipo_cliente',
            field=models.CharField(choices=[('DETAL', 'Al Detal'), ('MAYOR', 'Al por Mayor')], default='DETAL', max_length=10, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='precioespecial',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de Promoción'),
        ),
        migrations.AlterField(
            model_name='precioespecial',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Promoción'),
        ),
        migrations.AlterField(
            model_name='precioespecial',
            name='precio_especial',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Especial'),
        ),
        migrations.AlterField(
            model_name='precioespecial',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_especiales', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='precioespecial',
            name='tipo_cliente',
            field=models.CharField(choices=[('DETAL', 'Al Detal'), ('MAYOR', 'Al por Mayor')], max_length=10, verbose_name='Tipo de Cliente'),
        ),
    ]
