# Generated by Django 5.2.1 on 2025-07-02 12:02

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_base', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('nombre_display', models.CharField(blank=True, help_text="Nombre para mostrar, ej: 'Camisa Polo Azul'", max_length=255, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias_color', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Artículo por Color (para Fotos)',
                'verbose_name_plural': 'Artículos por Color (para Fotos)',
                'ordering': ['empresa', 'referencia_base', 'color'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=50, verbose_name='Referencia')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('talla', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('DAMA', 'Dama'), ('CABALLERO', 'Caballero'), ('UNISEX', 'Unisex')], db_index=True, default='UNISEX', max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unidad_medida', models.CharField(default='UND', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='clientes.empresa', verbose_name='Empresa Propietaria')),
                ('articulo_color_fotos', models.ForeignKey(blank=True, help_text='Se asigna automáticamente al guardar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='productos.referenciacolor', verbose_name='Agrupación de Fotos (Ref+Color)')),
            ],
            options={
                'verbose_name': 'Producto (Variante Específica)',
                'verbose_name_plural': 'Productos (Variantes Específicas)',
                'ordering': ['referencia', 'nombre', 'color', 'talla'],
                'permissions': [('upload_fotos_producto', 'Puede subir fotos para productos')],
            },
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=productos.models.ruta_guardado_foto_producto_agrupada, verbose_name='Archivo de Imagen')),
                ('descripcion_foto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Foto (Opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('empresa', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_productos', to='clientes.empresa')),
                ('referencia_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_agrupadas', to='productos.referenciacolor', verbose_name='Artículo por Color (Agrupador de Fotos)')),
            ],
            options={
                'verbose_name': 'Foto de Artículo (por Ref+Color)',
                'verbose_name_plural': 'Fotos de Artículos (por Ref+Color)',
                'ordering': ['referencia_color', 'orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='referenciacolor',
            constraint=models.UniqueConstraint(fields=('empresa', 'referencia_base', 'color'), name='agrupacion_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'referencia', 'talla', 'color'), name='variante_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False)), fields=('empresa', 'codigo_barras'), name='codigo_barras_unico_por_empresa'),
        ),
    ]
