# Generated by Django 5.2.1 on 2025-05-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(db_index=True, max_length=50, verbose_name='Referencia Base')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('talla', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Talla')),
                ('color', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Color')),
                ('genero', models.CharField(choices=[('DAMA', 'Dama'), ('CABALLERO', 'Caballero'), ('UNISEX', 'Unisex')], db_index=True, default='UNISEX', help_text='Género OBLIGATORIO al que pertenece la referencia', max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('unidad_medida', models.CharField(default='UND', max_length=20, verbose_name='Unidad de Medida')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en Bodega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='¿Está Activo?')),
                ('codigo_barras', models.CharField(blank=True, db_index=True, help_text='Código de barras único para esta variante de producto (Ref+Talla+Color).', max_length=100, null=True, unique=True, verbose_name='Código de Barras')),
            ],
            options={
                'verbose_name': 'Producto (Variante)',
                'verbose_name_plural': 'Productos (Variantes)',
                'ordering': ['referencia', 'nombre', 'color', 'talla'],
                'constraints': [models.UniqueConstraint(fields=('referencia', 'talla', 'color'), name='variante_unica'), models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False)), fields=('codigo_barras',), name='codigo_barras_unico_no_nulo')],
            },
        ),
    ]
