# Generated by Django 5.2.1 on 2025-05-20 04:49

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=productos.models.ruta_guardado_foto_producto_agrupada, verbose_name='Archivo de Imagen')),
                ('descripcion_foto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Foto (Opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='productos.producto', verbose_name='Producto (Variante) Asociado')),
            ],
            options={
                'verbose_name': 'Foto de Producto',
                'verbose_name_plural': 'Fotos de Productos',
                'ordering': ['producto', 'orden'],
            },
        ),
    ]
