# Generated by Django 5.2.1 on 2025-07-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.IntegerField(blank=True, null=True, verbose_name='Talla'),
        ),
    ]
