# Generated by Django 5.2.1 on 2025-10-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='permitir_preventa',
            field=models.BooleanField(default=False, help_text='Marcar esta opción si el producto está en producción y se puede vender sin tener stock físico.', verbose_name='Permitir Venta Sin Stock (Preventa)'),
        ),
    ]
