# Generated by Django 5.2.1 on 2025-05-20 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_fotoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_base', models.CharField(db_index=True, max_length=50, verbose_name='Referencia Base del Artículo')),
                ('color', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Color del Artículo')),
                ('nombre_display', models.CharField(blank=True, max_length=255, verbose_name='Nombre para Agrupación (Ref+Color)')),
            ],
            options={
                'verbose_name': 'Artículo por Color (para Fotos)',
                'verbose_name_plural': 'Artículos por Color (para Fotos)',
                'ordering': ['referencia_base', 'color'],
            },
        ),
        migrations.AlterModelOptions(
            name='fotoproducto',
            options={'ordering': ['articulo_agrupador', 'orden'], 'verbose_name': 'Foto de Artículo (por Ref+Color)', 'verbose_name_plural': 'Fotos de Artículos (por Ref+Color)'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['referencia', 'nombre', 'color', 'talla'], 'verbose_name': 'Producto (Variante Específica)', 'verbose_name_plural': 'Productos (Variantes Específicas)'},
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='variante_unica',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='codigo_barras_unico_no_nulo',
        ),
        migrations.RemoveField(
            model_name='fotoproducto',
            name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Color (Variante)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (Variante)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto (Variante)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Referencia Base (Variante)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Talla (Variante)'),
        ),
        migrations.AlterUniqueTogether(
            name='referenciacolor',
            unique_together={('referencia_base', 'color')},
        ),
        migrations.AddField(
            model_name='fotoproducto',
            name='articulo_agrupador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos_agrupadas', to='productos.referenciacolor', verbose_name='Artículo por Color (Agrupador de Fotos)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='articulo_color_fotos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='productos.referenciacolor', verbose_name='Agrupación Ref+Color (para Fotos)'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('referencia', 'talla', 'color'), name='variante_unica_productos_v2'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False)), fields=('codigo_barras',), name='codigo_barras_unico_no_nulo_productos_v2'),
        ),
    ]
