# Generated by Django 5.2.1 on 2025-07-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_talla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['referencia', 'nombre', 'color', 'talla'], 'permissions': [('upload_fotos_producto', 'Puede subir fotos para productos'), ('view_inventory_report', 'Puede ver el informe de inventario físico')], 'verbose_name': 'Producto (Variante Específica)', 'verbose_name_plural': 'Productos (Variantes Específicas)'},
        ),
    ]
