# Generated by Django 5.2.1 on 2025-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_permitir_preventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(default='UNISEX', help_text='Ej: DAMA, CABALLERO, NIÑO, PLUS. Debe coincidir con la configuración de la empresa.', max_length=20, verbose_name='Categoría/Género'),
        ),
    ]
