# Generated by Django 5.2.1 on 2025-09-11 21:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Stock'),
        ),
    ]
