# Generated by Django 5.2.1 on 2026-05-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_producto_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="genero",
            field=models.CharField(
                choices=[
                    ("DAMA", "DAMA"),
                    ("CABALLERO", "CABALLERO"),
                    ("NIÑO", "NIÑO"),
                    ("NIÑA", "NIÑA"),
                    ("UNISEX", "UNISEX"),
                ],
                default="UNISEX",
                help_text="Seleccione la categoría o género.",
                max_length=20,
                verbose_name="Categoría/Género",
            ),
        ),
    ]
