# Generated by Django 5.2.1 on 2026-07-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oculto_para_standar',
            field=models.BooleanField(default=False),
        ),
    ]
