# Generated by Django 5.2.1 on 2026-07-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_oculto_para_standar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='shopify_inventory_item_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Inventario Shopify'),
        ),
        migrations.AddField(
            model_name='producto',
            name='shopify_variant_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Variante Shopify'),
        ),
    ]
