# Generated by Django 5.2.1 on 2025-05-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_limpiar_fotos_huerfanas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['referencia', 'nombre', 'color', 'talla'], 'permissions': [('upload_fotos_producto', 'Puede subir fotos para productos')], 'verbose_name': 'Producto (Variante Específica)', 'verbose_name_plural': 'Productos (Variantes Específicas)'},
        ),
    ]
