# Generated by Django 5.2.1 on 2026-07-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_shopify_inventory_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('DAMA', 'Dama'), ('CABALLERO', 'Caballero'), ('NIÑO', 'Niño'), ('NIÑA', 'Niña'), ('PLUS', 'Plus'), ('UNISEX', 'Unisex')], default='CABALLERO', help_text='Seleccione el género o categoría del producto.', max_length=20, verbose_name='Categoría/Género'),
        ),
    ]
