# Generated by Django 5.2.1 on 2026-07-15 22:46
# Ajustado a mano: el campo 'ubicacion' pasa de texto libre a FK a Bodega.
# Se elimina y se vuelve a crear (en vez de un AlterField) porque el
# contenido de texto libre anterior no es un ID de bodega válido y el
# usuario decidió descartarlo (todo producto queda apuntando a la
# Bodega Principal vía la migración de datos 0008_backfill_bodega_principal
# de la app 'bodega').

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_alter_personalbodega_options_and_more'),
        ('productos', '0007_alter_producto_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='bodega.bodega', verbose_name='Bodega'),
        ),
    ]
