# Generated by Django 5.2.1 on 2026-07-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_usa_shopify'),
        ('productos', '0008_alter_producto_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Color')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='color_temp',
            field=models.ForeignKey(blank=True, help_text="Campo temporal de migración; reemplazará al 'color' de texto libre.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_temp', to='productos.color', verbose_name='Color (nuevo)'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='color_unico_por_empresa'),
        ),
    ]
