# Generated by Django 5.2.1 on 2026-07-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_descripcion',
            field=models.TextField(blank=True, help_text='Si se deja vacío, se usa la descripción interna del producto.', null=True, verbose_name='Descripción para Shopify'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, se usa el precio de venta interno.', max_digits=10, null=True, verbose_name='Precio para Shopify'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de Producto en Shopify'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_titulo',
            field=models.CharField(blank=True, help_text='Si se deja vacío, se usa el nombre interno del producto.', max_length=255, null=True, verbose_name='Título para Shopify'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_ultima_sincronizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización con Shopify'),
        ),
    ]
