# Generated by Django 5.2.1 on 2026-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_referenciacolor_shopify_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_categoria_id',
            field=models.CharField(blank=True, help_text="GID de la categoría oficial de la taxonomía de Shopify (ej. 'gid://shopify/TaxonomyCategory/aa-1-12-4').", max_length=100, null=True, verbose_name='ID de Categoría (Shopify)'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_categoria_nombre',
            field=models.CharField(blank=True, help_text="Solo para mostrar en pantalla (ej. 'Apparel & Accessories > Clothing > Pants > Jeans').", max_length=255, null=True, verbose_name='Nombre de Categoría (Shopify)'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_tipo',
            field=models.CharField(blank=True, help_text="Campo de texto libre de Shopify ('product_type'), ej. 'Skinny jean'.", max_length=255, null=True, verbose_name='Tipo (Shopify)'),
        ),
    ]
