# Generated by Django 5.2.1 on 2026-07-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_referenciacolor_shopify_categoria_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_colecciones_ids',
            field=models.CharField(blank=True, help_text='GIDs de colección separados por coma. Uso interno, se sincroniza junto con shopify_colecciones_nombres.', max_length=1000, null=True, verbose_name='IDs de Colecciones (Shopify)'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_colecciones_nombres',
            field=models.CharField(blank=True, help_text='Solo para mostrar en pantalla, en el mismo orden que shopify_colecciones_ids.', max_length=1000, null=True, verbose_name='Nombres de Colecciones (Shopify)'),
        ),
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_etiquetas',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por coma. El color se agrega siempre como etiqueta automática, además de estas.', max_length=500, null=True, verbose_name='Etiquetas adicionales (Shopify)'),
        ),
    ]
