# Generated by Django 5.2.1 on 2026-07-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_referenciacolor_shopify_colecciones_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciacolor',
            name='shopify_borrador_por_agotado',
            field=models.BooleanField(default=False, help_text='Marca si el sistema pasó este producto a borrador automáticamente por quedarse sin stock disponible para Web. Permite reactivarlo solo (sin tocar productos que la administradora archivó por otro motivo).', verbose_name='En borrador por falta de stock'),
        ),
    ]
