# Generated by Django 5.2.1 on 2026-07-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0005_producto_oculto_para_standar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_customer_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(default='Cliente Anónimo', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección de Envío')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento/Estado')),
                ('pais', models.CharField(blank=True, default='Colombia', max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cliente Web',
                'verbose_name_plural': 'Clientes Web',
            },
        ),
        migrations.CreateModel(
            name='PedidoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.CharField(max_length=50, unique=True, verbose_name='ID Pedido Shopify')),
                ('numero_orden', models.CharField(max_length=50, verbose_name='Número de Orden (Ej: #1001)')),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de Compra')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Pagado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('despachado', models.BooleanField(default=False, verbose_name='¿Despachado en Bodega?')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos_web.clienteweb')),
            ],
            options={
                'verbose_name': 'Pedido Web',
                'verbose_name_plural': 'Pedidos Web',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_variant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_producto_shopify', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto', verbose_name='Producto Interno')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos_web.pedidoweb')),
            ],
        ),
    ]
