# Generated by Django 5.2.1 on 2026-07-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoweb',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detallepedidoweb',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedidoweb',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ClienteWeb',
        ),
        migrations.DeleteModel(
            name='PedidoWeb',
        ),
        migrations.DeleteModel(
            name='DetallePedidoWeb',
        ),
    ]
