# Generated by Django 5.2.1 on 2025-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='categorias_tallas',
            field=models.JSONField(blank=True, help_text='Define las categorías de productos y sus tallas para los PDFs. \n                     Formato: {"NOMBRE_CATEGORIA": ["talla1", "talla2"], ...}. \n                     Ej: {"DAMA": ["3", "5", "7"], "NIÑO": ["2", "4", "6"]}', null=True, verbose_name='Configuración de Categorías y Tallas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='talla_mapeo',
            field=models.JSONField(blank=True, help_text='Ej: {"6": "3", "8": "5", "10": "7", "12": "9", "14": "11", "16": "13"}', null=True, verbose_name='Mapeo de Tallas Dama'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tallas_dama_display',
            field=models.JSONField(blank=True, help_text='Lista ordenada para mostrar. Ej: ["3", "5", "7", "9", "11", "13"]', null=True, verbose_name='Tallas Dama (Encabezados PDF/Pedido)'),
        ),
    ]
