# Generated by Django 5.2.1 on 2025-07-07 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsable_de_iva',
            field=models.BooleanField(default=True, verbose_name='Responsable de IVA'),
        ),
    ]
