# Generated by Django 5.2.1 on 2025-10-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_empresa_categorias_tallas_empresa_talla_mapeo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tallas_dama_display',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='talla_mapeo',
            field=models.JSONField(blank=True, help_text='OPCIONAL. Traduce tallas internas a tallas de muestra. Ej: {"6": "3", "8": "5"}', null=True, verbose_name='Mapeo de Tallas (Traducción)'),
        ),
    ]
