# Generated by Django 5.2.1 on 2026-07-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_empresa_tallas_dama_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='banner_inicio',
            field=models.ImageField(blank=True, help_text='Imagen de fondo del banner en la página principal. Recomendado: ancho grande, ej. 1920x600px.', null=True, upload_to='banners/', verbose_name='Banner de Inicio'),
        ),
    ]
