# Generated by Django 5.2.1 on 2025-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_empresa_ciudad_empresa_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
    ]
