# Generated by Django 5.2.1 on 2026-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_empresa_banner_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usa_shopify',
            field=models.BooleanField(default=False, help_text='Activa el panel de sincronización con Shopify para esta empresa.', verbose_name='¿Usa integración con Shopify?'),
        ),
    ]
