# Generated by Django 5.2.1 on 2026-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_usa_shopify'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ultimo_consecutivo_ean13',
            field=models.PositiveIntegerField(default=0, help_text='Uso interno: no editar manualmente. Se incrementa cada vez que se genera un código EAN13 nuevo.', verbose_name='Último Consecutivo EAN13'),
        ),
    ]
