# Generated by Django 5.2.1 on 2026-07-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_empresa_ultimo_consecutivo_ean13'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_ean13_empresa',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Uso interno: no editar manualmente. Bloque de 3 dígitos que identifica a esta empresa dentro de los EAN13 generados automáticamente, para que nunca se crucen con los de otra empresa. Se asigna solo. Rango válido: 1-999.', null=True, unique=True, verbose_name='Código EAN13 de Empresa'),
        ),
    ]
