# Generated by Django 5.2.1 on 2026-07-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_regenerar_todos_los_ean13'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_accion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Acción en curso'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_activo',
            field=models.BooleanField(default=False, verbose_name='Sincronización Shopify en curso'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_actualizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_errores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_exitosos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_mensaje',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_procesados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empresa',
            name='shopify_sync_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
