# Generated by Django 5.2.1 on 2026-08-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_empresa_shopify_sync_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='talla_mapeo_shopify',
            field=models.JSONField(blank=True, help_text='OPCIONAL. Independiente del \'Mapeo de Tallas\' de los PDFs -- solo afecta la talla (option1) que se sube a Shopify. Clave = talla interna, valor = talla que debe mostrar Shopify. Ej: {"3": "6", "5": "8", "7": "10"}', null=True, verbose_name='Mapeo de Tallas para Shopify'),
        ),
    ]
