# Generated by Django 5.2.1 on 2026-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioalmacen',
            name='oculto_para_standar',
            field=models.BooleanField(default=False),
        ),
    ]
