from modulos.carrito import Carrito
from repositories.producto_repo import ProductoRepository
from repositories.venta_repo import VentaRepository
from modulos.dialogs.seleccion_dialog import DialogSeleccion
from modulos.dialogs.cobro_dialog import VentanaCobro, VentanaComprobante