# Generated by Django 5.2.1 on 2025-09-24 11:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Reportada por Vendedor')),
                ('cantidad_recibida_bodega', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida en Bodega')),
                ('estado_producto', models.CharField(choices=[('BUENO', 'Buen estado (Reingresa a stock)'), ('DEFECTUOSO', 'Defectuoso (Revisión/Reparación)'), ('DESECHAR', 'Para Desechar')], default='BUENO', max_length=15, verbose_name='Estado del Producto Devuelto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_devueltos', to='productos.producto', verbose_name='Producto Devuelto')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
            },
        ),
        migrations.CreateModel(
            name='DevolucionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Devolución')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo General')),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada por Vendedor'), ('RECIBIDA_EN_BODEGA', 'Recibida en Bodega'), ('VERIFICADA', 'Verificada y Finalizada'), ('CON_DIFERENCIAS', 'Verificada con Diferencias')], default='INICIADA', max_length=20, verbose_name='Estado de la Devolución')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='clientes.cliente', verbose_name='Cliente que Devuelve')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Devolución de Cliente',
                'verbose_name_plural': 'Devoluciones de Clientes',
                'ordering': ['-empresa', '-fecha_hora'],
                'permissions': [('can_receive_devolucion', 'Puede recibir y verificar devoluciones en bodega')],
            },
        ),
    ]
