# Generated by Django 5.2.1 on 2025-05-17 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Devolución')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo General')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='clientes.cliente', verbose_name='Cliente que Devuelve')),
                ('pedido_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_asociadas', to='pedidos.pedido', verbose_name='Pedido Original (Opcional)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Procesa')),
            ],
            options={
                'verbose_name': 'Devolución de Cliente',
                'verbose_name_plural': 'Devoluciones de Clientes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Devuelta')),
                ('estado_producto', models.CharField(choices=[('BUENO', 'Buen estado (Reingresa a stock)'), ('DEFECTUOSO', 'Defectuoso (Revisión/Reparación)'), ('DESECHAR', 'Para Desechar')], default='BUENO', max_length=15, verbose_name='Estado del Producto Devuelto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_devueltos', to='productos.producto', verbose_name='Producto Devuelto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='devoluciones.devolucioncliente', verbose_name='Devolución Asociada')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
                'unique_together': {('devolucion', 'producto')},
            },
        ),
    ]
