# Generated by Django 5.2.1 on 2025-09-24 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devoluciones', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucioncliente',
            name='pedido_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_asociadas', to='pedidos.pedido', verbose_name='Pedido Original (Opcional)'),
        ),
        migrations.AddField(
            model_name='devolucioncliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Procesa'),
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='devoluciones.devolucioncliente', verbose_name='Devolución Asociada'),
        ),
        migrations.AddConstraint(
            model_name='detalledevolucion',
            constraint=models.UniqueConstraint(fields=('devolucion', 'producto', 'estado_producto'), name='devolucion_producto_estado_unico'),
        ),
    ]
