# Generated by Django 5.2.1 on 2025-07-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledevolucion',
            name='cantidad_recibida_bodega',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida en Bodega'),
        ),
        migrations.AddField(
            model_name='devolucioncliente',
            name='estado',
            field=models.CharField(choices=[('INICIADA', 'Iniciada por Vendedor'), ('RECIBIDA_EN_BODEGA', 'Recibida en Bodega'), ('VERIFICADA', 'Verificada y Finalizada'), ('CON_DIFERENCIAS', 'Verificada con Diferencias')], default='INICIADA', max_length=20, verbose_name='Estado de la Devolución'),
        ),
        migrations.AlterField(
            model_name='detalledevolucion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Reportada por Vendedor'),
        ),
    ]
