# Generated by Django 5.2.1 on 2026-07-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledevolucion',
            name='estado_producto',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión en Bodega'), ('BUENO', 'Buen estado (Reingresa a stock)'), ('DEFECTUOSO', 'Defectuoso (Revisión/Reparación)'), ('DESECHAR', 'Para Desechar')], default='PENDIENTE', help_text='Lo define el vendedor al crear la devolución; Bodega lo revisa físicamente y lo confirma al recibirla.', max_length=15, verbose_name='Estado del Producto Devuelto'),
        ),
    ]
