# Generated by Django 5.2.1 on 2025-07-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0002_detalledevolucion_cantidad_recibida_bodega_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucioncliente',
            options={'ordering': ['-empresa', '-fecha_hora'], 'permissions': [('can_receive_devolucion', 'Puede recibir y verificar devoluciones en bodega')], 'verbose_name': 'Devolución de Cliente', 'verbose_name_plural': 'Devoluciones de Clientes'},
        ),
    ]
